// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAllowlistEntry = `-- name: AddAllowlistEntry :one
INSERT INTO admin_allowlist (github_id, github_login, note, added_by) VALUES ($1, $2, $3, $4)
ON CONFLICT (github_id) DO UPDATE SET github_login = EXCLUDED.github_login, note = EXCLUDED.note
RETURNING github_id, github_login, note, added_by, added_at
`

type AddAllowlistEntryParams struct {
	GithubID    int64
	GithubLogin pgtype.Text
	Note        pgtype.Text
	AddedBy     uuid.UUID
}

func (q *Queries) AddAllowlistEntry(ctx context.Context, arg AddAllowlistEntryParams) (AdminAllowlist, error) {
	row := q.db.QueryRow(ctx, addAllowlistEntry,
		arg.GithubID,
		arg.GithubLogin,
		arg.Note,
		arg.AddedBy,
	)
	var i AdminAllowlist
	err := row.Scan(
		&i.GithubID,
		&i.GithubLogin,
		&i.Note,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (user_id, github_id, github_login, email, role, permissions)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, github_id, github_login, email, role, permissions, created_at, updated_at
`

type CreateAdminParams struct {
	UserID      uuid.UUID
	GithubID    pgtype.Int8
	GithubLogin pgtype.Text
	Email       pgtype.Text
	Role        string
	Permissions []byte
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.UserID,
		arg.GithubID,
		arg.GithubLogin,
		arg.Email,
		arg.Role,
		arg.Permissions,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdminByGitHubID = `-- name: GetAdminByGitHubID :one
SELECT id, user_id, github_id, github_login, email, role, permissions, created_at, updated_at FROM admins WHERE github_id = $1 LIMIT 1
`

func (q *Queries) GetAdminByGitHubID(ctx context.Context, githubID pgtype.Int8) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByGitHubID, githubID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByUserID = `-- name: GetAdminByUserID :one
SELECT id, user_id, github_id, github_login, email, role, permissions, created_at, updated_at FROM admins WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetAdminByUserID(ctx context.Context, userID uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByUserID, userID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isGitHubAllowlisted = `-- name: IsGitHubAllowlisted :one
SELECT EXISTS(
    SELECT 1 FROM admin_allowlist WHERE github_id = $1
) as allowlisted
`

func (q *Queries) IsGitHubAllowlisted(ctx context.Context, githubID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isGitHubAllowlisted, githubID)
	var allowlisted bool
	err := row.Scan(&allowlisted)
	return allowlisted, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, user_id, github_id, github_login, email, role, permissions, created_at, updated_at FROM admins ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListAdminsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error) {
	rows, err := q.db.Query(ctx, listAdmins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admin
	for rows.Next() {
		var i Admin
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GithubID,
			&i.GithubLogin,
			&i.Email,
			&i.Role,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllowlist = `-- name: ListAllowlist :many
SELECT github_id, github_login, note, added_by, added_at FROM admin_allowlist ORDER BY added_at DESC LIMIT $1 OFFSET $2
`

type ListAllowlistParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAllowlist(ctx context.Context, arg ListAllowlistParams) ([]AdminAllowlist, error) {
	rows, err := q.db.Query(ctx, listAllowlist, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAllowlist
	for rows.Next() {
		var i AdminAllowlist
		if err := rows.Scan(
			&i.GithubID,
			&i.GithubLogin,
			&i.Note,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllowlistEntry = `-- name: RemoveAllowlistEntry :exec
DELETE FROM admin_allowlist WHERE github_id = $1
`

func (q *Queries) RemoveAllowlistEntry(ctx context.Context, githubID int64) error {
	_, err := q.db.Exec(ctx, removeAllowlistEntry, githubID)
	return err
}

const updateAdminPermissions = `-- name: UpdateAdminPermissions :one
UPDATE admins SET permissions = $2, role = $3, updated_at = NOW() WHERE id = $1 RETURNING id, user_id, github_id, github_login, email, role, permissions, created_at, updated_at
`

type UpdateAdminPermissionsParams struct {
	ID          pgtype.UUID
	Permissions []byte
	Role        string
}

func (q *Queries) UpdateAdminPermissions(ctx context.Context, arg UpdateAdminPermissionsParams) (Admin, error) {
	row := q.db.QueryRow(ctx, updateAdminPermissions, arg.ID, arg.Permissions, arg.Role)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdmin = `-- name: UpsertAdmin :one
INSERT INTO admins (user_id, github_id, github_login, email, role, permissions)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) DO UPDATE SET
    github_login = EXCLUDED.github_login,
    email = EXCLUDED.email,
    role = EXCLUDED.role,
    permissions = COALESCE(EXCLUDED.permissions, admins.permissions),
    updated_at = NOW()
RETURNING id, user_id, github_id, github_login, email, role, permissions, created_at, updated_at
`

type UpsertAdminParams struct {
	UserID      uuid.UUID
	GithubID    pgtype.Int8
	GithubLogin pgtype.Text
	Email       pgtype.Text
	Role        string
	Permissions []byte
}

func (q *Queries) UpsertAdmin(ctx context.Context, arg UpsertAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, upsertAdmin,
		arg.UserID,
		arg.GithubID,
		arg.GithubLogin,
		arg.Email,
		arg.Role,
		arg.Permissions,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
