// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_dashboard.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM users)::int AS total_users,
    (SELECT COUNT(*) FROM jobs WHERE status = 'published')::int AS active_jobs,
    (SELECT COUNT(*) FROM job_applications WHERE status IN ('submitted', 'quiz_completed', 'under_review'))::int AS pending_applications,
    (SELECT COUNT(*) FROM job_applications WHERE status != 'draft')::int AS total_applications,
    (SELECT COUNT(*) FROM users WHERE created_at >= CURRENT_DATE)::int AS new_users_today,
    (SELECT COUNT(*) FROM job_applications WHERE submitted_at >= CURRENT_DATE)::int AS new_applications_today
`

type GetDashboardStatsRow struct {
	TotalUsers           int32
	ActiveJobs           int32
	PendingApplications  int32
	TotalApplications    int32
	NewUsersToday        int32
	NewApplicationsToday int32
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveJobs,
		&i.PendingApplications,
		&i.TotalApplications,
		&i.NewUsersToday,
		&i.NewApplicationsToday,
	)
	return i, err
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT
    u.github_username,
    u.avatar_url,
    ja.status,
    ja.submitted_at,
    j.title AS job_title
FROM job_applications ja
JOIN users u ON ja.user_id = u.id
JOIN jobs j ON ja.job_id = j.id
WHERE ja.submitted_at IS NOT NULL
ORDER BY ja.submitted_at DESC
LIMIT $1
`

type GetRecentActivityRow struct {
	GithubUsername string
	AvatarUrl      pgtype.Text
	Status         ApplicationStatus
	SubmittedAt    pgtype.Timestamp
	JobTitle       string
}

func (q *Queries) GetRecentActivity(ctx context.Context, limit int32) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.GithubUsername,
			&i.AvatarUrl,
			&i.Status,
			&i.SubmittedAt,
			&i.JobTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
