// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_summaries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAISummary = `-- name: CreateAISummary :one
INSERT INTO ai_summaries (user_id, summary, strengths, weaknesses, model, cv_version)
VALUES ($1, $2, $3, $4, $5, $6)

RETURNING id, user_id, summary, strengths, weaknesses, model, created_at, cv_version
`

type CreateAISummaryParams struct {
	UserID     uuid.UUID
	Summary    []byte
	Strengths  pgtype.Text
	Weaknesses pgtype.Text
	Model      pgtype.Text
	CvVersion  pgtype.Int4
}

func (q *Queries) CreateAISummary(ctx context.Context, arg CreateAISummaryParams) (AiSummary, error) {
	row := q.db.QueryRow(ctx, createAISummary,
		arg.UserID,
		arg.Summary,
		arg.Strengths,
		arg.Weaknesses,
		arg.Model,
		arg.CvVersion,
	)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.Strengths,
		&i.Weaknesses,
		&i.Model,
		&i.CreatedAt,
		&i.CvVersion,
	)
	return i, err
}

const getAISummaryByCVVersion = `-- name: GetAISummaryByCVVersion :one
SELECT id, user_id, summary, strengths, weaknesses, model, created_at, cv_version FROM ai_summaries
WHERE user_id = $1 AND cv_version = $2
`

type GetAISummaryByCVVersionParams struct {
	UserID    uuid.UUID
	CvVersion pgtype.Int4
}

func (q *Queries) GetAISummaryByCVVersion(ctx context.Context, arg GetAISummaryByCVVersionParams) (AiSummary, error) {
	row := q.db.QueryRow(ctx, getAISummaryByCVVersion, arg.UserID, arg.CvVersion)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.Strengths,
		&i.Weaknesses,
		&i.Model,
		&i.CreatedAt,
		&i.CvVersion,
	)
	return i, err
}

const getLatestAISummary = `-- name: GetLatestAISummary :one
SELECT id, user_id, summary, strengths, weaknesses, model, created_at, cv_version FROM ai_summaries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAISummary(ctx context.Context, userID uuid.UUID) (AiSummary, error) {
	row := q.db.QueryRow(ctx, getLatestAISummary, userID)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.Strengths,
		&i.Weaknesses,
		&i.Model,
		&i.CreatedAt,
		&i.CvVersion,
	)
	return i, err
}
