// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_summaries.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAISummary = `-- name: CreateAISummary :one
INSERT INTO ai_summaries (
    user_id,
    summary,
    strengths,
    weaknesses,
    model
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, summary, strengths, weaknesses, model, created_at
`

type CreateAISummaryParams struct {
	UserID     uuid.UUID
	Summary    pgtype.Text
	Strengths  pgtype.Text
	Weaknesses pgtype.Text
	Model      pgtype.Text
}

func (q *Queries) CreateAISummary(ctx context.Context, arg CreateAISummaryParams) (AiSummary, error) {
	row := q.db.QueryRow(ctx, createAISummary,
		arg.UserID,
		arg.Summary,
		arg.Strengths,
		arg.Weaknesses,
		arg.Model,
	)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.Strengths,
		&i.Weaknesses,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestAISummary = `-- name: GetLatestAISummary :one
SELECT id, user_id, summary, strengths, weaknesses, model, created_at FROM ai_summaries
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestAISummary(ctx context.Context, userID uuid.UUID) (AiSummary, error) {
	row := q.db.QueryRow(ctx, getLatestAISummary, userID)
	var i AiSummary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Summary,
		&i.Strengths,
		&i.Weaknesses,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
