// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptApplication = `-- name: AcceptApplication :one
UPDATE job_applications
SET 
    status = 'accepted',
    updated_at = NOW()
WHERE id = $1 AND status IN ('under_review', 'shortlisted', 'interviewed')
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

func (q *Queries) AcceptApplication(ctx context.Context, id pgtype.UUID) (JobApplication, error) {
	row := q.db.QueryRow(ctx, acceptApplication, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addEmployerFeedback = `-- name: AddEmployerFeedback :one
UPDATE job_applications
SET 
    employer_feedback = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type AddEmployerFeedbackParams struct {
	ID               pgtype.UUID
	EmployerFeedback pgtype.Text
}

func (q *Queries) AddEmployerFeedback(ctx context.Context, arg AddEmployerFeedbackParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, addEmployerFeedback, arg.ID, arg.EmployerFeedback)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applicationCompleteQuiz = `-- name: ApplicationCompleteQuiz :one
UPDATE job_applications
SET 
    status = 'quiz_completed',
    quiz_score = $2,
    quiz_completed_at = NOW(),
    quiz_passed = $3,
    updated_at = NOW()
WHERE id = $1 AND status = 'quiz_started'
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type ApplicationCompleteQuizParams struct {
	ID         pgtype.UUID
	QuizScore  pgtype.Int4
	QuizPassed pgtype.Bool
}

func (q *Queries) ApplicationCompleteQuiz(ctx context.Context, arg ApplicationCompleteQuizParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, applicationCompleteQuiz, arg.ID, arg.QuizScore, arg.QuizPassed)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applicationStartQuiz = `-- name: ApplicationStartQuiz :one
UPDATE job_applications
SET 
    status = 'quiz_started',
    quiz_id = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'submitted'
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type ApplicationStartQuizParams struct {
	ID     pgtype.UUID
	QuizID uuid.UUID
}

func (q *Queries) ApplicationStartQuiz(ctx context.Context, arg ApplicationStartQuizParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, applicationStartQuiz, arg.ID, arg.QuizID)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApplication = `-- name: CreateApplication :one

INSERT INTO job_applications (
    job_id, user_id, 
    github_username, github_id, applicant_email, applicant_name, applicant_avatar_url,
    cover_letter, proposed_salary, proposed_salary_currency, availability_date,
    portfolio_url, linkedin_url, notes, status, submitted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type CreateApplicationParams struct {
	JobID                  pgtype.UUID
	UserID                 pgtype.UUID
	GithubUsername         string
	GithubID               int64
	ApplicantEmail         pgtype.Text
	ApplicantName          pgtype.Text
	ApplicantAvatarUrl     pgtype.Text
	CoverLetter            pgtype.Text
	ProposedSalary         pgtype.Int4
	ProposedSalaryCurrency pgtype.Text
	AvailabilityDate       pgtype.Timestamp
	PortfolioUrl           pgtype.Text
	LinkedinUrl            pgtype.Text
	Notes                  pgtype.Text
	Status                 ApplicationStatus
	SubmittedAt            pgtype.Timestamp
}

// Application CRUD operations
func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.JobID,
		arg.UserID,
		arg.GithubUsername,
		arg.GithubID,
		arg.ApplicantEmail,
		arg.ApplicantName,
		arg.ApplicantAvatarUrl,
		arg.CoverLetter,
		arg.ProposedSalary,
		arg.ProposedSalaryCurrency,
		arg.AvailabilityDate,
		arg.PortfolioUrl,
		arg.LinkedinUrl,
		arg.Notes,
		arg.Status,
		arg.SubmittedAt,
	)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftApplication = `-- name: DeleteDraftApplication :exec
DELETE FROM job_applications
WHERE id = $1 AND user_id = $2 AND status = 'draft'
`

type DeleteDraftApplicationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteDraftApplication(ctx context.Context, arg DeleteDraftApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteDraftApplication, arg.ID, arg.UserID)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at FROM job_applications WHERE id = $1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id pgtype.UUID) (JobApplication, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByJobAndUser = `-- name: GetApplicationByJobAndUser :one
SELECT id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at FROM job_applications 
WHERE job_id = $1 AND user_id = $2 
LIMIT 1
`

type GetApplicationByJobAndUserParams struct {
	JobID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetApplicationByJobAndUser(ctx context.Context, arg GetApplicationByJobAndUserParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, getApplicationByJobAndUser, arg.JobID, arg.UserID)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationCountsByJob = `-- name: GetApplicationCountsByJob :one
SELECT 
    COUNT(*) as total_applications,
    COUNT(CASE WHEN status = 'submitted' THEN 1 END) as submitted,
    COUNT(CASE WHEN status = 'quiz_completed' THEN 1 END) as quiz_completed,
    COUNT(CASE WHEN status = 'under_review' THEN 1 END) as under_review,
    COUNT(CASE WHEN status = 'shortlisted' THEN 1 END) as shortlisted,
    COUNT(CASE WHEN status = 'accepted' THEN 1 END) as accepted,
    COUNT(CASE WHEN status = 'rejected' THEN 1 END) as rejected
FROM job_applications
WHERE job_id = $1
`

type GetApplicationCountsByJobRow struct {
	TotalApplications int64
	Submitted         int64
	QuizCompleted     int64
	UnderReview       int64
	Shortlisted       int64
	Accepted          int64
	Rejected          int64
}

func (q *Queries) GetApplicationCountsByJob(ctx context.Context, jobID pgtype.UUID) (GetApplicationCountsByJobRow, error) {
	row := q.db.QueryRow(ctx, getApplicationCountsByJob, jobID)
	var i GetApplicationCountsByJobRow
	err := row.Scan(
		&i.TotalApplications,
		&i.Submitted,
		&i.QuizCompleted,
		&i.UnderReview,
		&i.Shortlisted,
		&i.Accepted,
		&i.Rejected,
	)
	return i, err
}

const getApplicationWithDetails = `-- name: GetApplicationWithDetails :one
SELECT 
    a.id, a.job_id, a.user_id, a.github_username, a.github_id, a.applicant_email, a.applicant_name, a.applicant_avatar_url, a.cover_letter, a.proposed_salary, a.proposed_salary_currency, a.availability_date, a.portfolio_url, a.linkedin_url, a.notes, a.status, a.submitted_at, a.reviewed_at, a.reviewed_by, a.employer_feedback, a.rejection_reason, a.quiz_id, a.quiz_score, a.quiz_completed_at, a.quiz_passed, a.can_view_ai_summary, a.created_at, a.updated_at,
    j.title as job_title,
    j.company as job_company,
    j.location as job_location,
    j.job_type,
    u.github_username as user_github_username,
    u.avatar_url as user_avatar_url
FROM job_applications a
JOIN jobs j ON a.job_id = j.id
JOIN users u ON a.user_id = u.id
WHERE a.id = $1
`

type GetApplicationWithDetailsRow struct {
	ID                     pgtype.UUID
	JobID                  pgtype.UUID
	UserID                 pgtype.UUID
	GithubUsername         string
	GithubID               int64
	ApplicantEmail         pgtype.Text
	ApplicantName          pgtype.Text
	ApplicantAvatarUrl     pgtype.Text
	CoverLetter            pgtype.Text
	ProposedSalary         pgtype.Int4
	ProposedSalaryCurrency pgtype.Text
	AvailabilityDate       pgtype.Timestamp
	PortfolioUrl           pgtype.Text
	LinkedinUrl            pgtype.Text
	Notes                  pgtype.Text
	Status                 ApplicationStatus
	SubmittedAt            pgtype.Timestamp
	ReviewedAt             pgtype.Timestamp
	ReviewedBy             uuid.UUID
	EmployerFeedback       pgtype.Text
	RejectionReason        pgtype.Text
	QuizID                 uuid.UUID
	QuizScore              pgtype.Int4
	QuizCompletedAt        pgtype.Timestamp
	QuizPassed             pgtype.Bool
	CanViewAiSummary       pgtype.Bool
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	JobTitle               string
	JobCompany             string
	JobLocation            pgtype.Text
	JobType                JobType
	UserGithubUsername     string
	UserAvatarUrl          pgtype.Text
}

func (q *Queries) GetApplicationWithDetails(ctx context.Context, id pgtype.UUID) (GetApplicationWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getApplicationWithDetails, id)
	var i GetApplicationWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JobTitle,
		&i.JobCompany,
		&i.JobLocation,
		&i.JobType,
		&i.UserGithubUsername,
		&i.UserAvatarUrl,
	)
	return i, err
}

const getRecentApplications = `-- name: GetRecentApplications :many
SELECT id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at FROM job_applications
WHERE submitted_at > NOW() - interval '7 days'
ORDER BY submitted_at DESC
LIMIT $1
`

func (q *Queries) GetRecentApplications(ctx context.Context, limit int32) ([]JobApplication, error) {
	rows, err := q.db.Query(ctx, getRecentApplications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserApplicationStats = `-- name: GetUserApplicationStats :many
SELECT 
    j.company,
    j.title,
    a.status,
    a.submitted_at,
    a.quiz_score,
    a.quiz_passed
FROM job_applications a
JOIN jobs j ON a.job_id = j.id
WHERE a.user_id = $1
ORDER BY a.submitted_at DESC
`

type GetUserApplicationStatsRow struct {
	Company     string
	Title       string
	Status      ApplicationStatus
	SubmittedAt pgtype.Timestamp
	QuizScore   pgtype.Int4
	QuizPassed  pgtype.Bool
}

func (q *Queries) GetUserApplicationStats(ctx context.Context, userID pgtype.UUID) ([]GetUserApplicationStatsRow, error) {
	rows, err := q.db.Query(ctx, getUserApplicationStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserApplicationStatsRow
	for rows.Next() {
		var i GetUserApplicationStatsRow
		if err := rows.Scan(
			&i.Company,
			&i.Title,
			&i.Status,
			&i.SubmittedAt,
			&i.QuizScore,
			&i.QuizPassed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserApplied = `-- name: HasUserApplied :one

SELECT EXISTS(
    SELECT 1 FROM job_applications 
    WHERE job_id = $1 AND user_id = $2
) AS has_applied
`

type HasUserAppliedParams struct {
	JobID  pgtype.UUID
	UserID pgtype.UUID
}

// Check/Validation Queries
func (q *Queries) HasUserApplied(ctx context.Context, arg HasUserAppliedParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserApplied, arg.JobID, arg.UserID)
	var has_applied bool
	err := row.Scan(&has_applied)
	return has_applied, err
}

const listApplicationsByJob = `-- name: ListApplicationsByJob :many
SELECT 
    a.id, a.job_id, a.user_id, a.github_username, a.github_id, a.applicant_email, a.applicant_name, a.applicant_avatar_url, a.cover_letter, a.proposed_salary, a.proposed_salary_currency, a.availability_date, a.portfolio_url, a.linkedin_url, a.notes, a.status, a.submitted_at, a.reviewed_at, a.reviewed_by, a.employer_feedback, a.rejection_reason, a.quiz_id, a.quiz_score, a.quiz_completed_at, a.quiz_passed, a.can_view_ai_summary, a.created_at, a.updated_at,
    u.github_username,
    u.avatar_url,
    u.email,
    u.name
FROM job_applications a
JOIN users u ON a.user_id = u.id
WHERE a.job_id = $1
ORDER BY 
    CASE a.status::text
        WHEN 'draft' THEN 1
        WHEN 'submitted' THEN 2
        WHEN 'quiz_started' THEN 3
        WHEN 'quiz_completed' THEN 4
        WHEN 'under_review' THEN 5
        WHEN 'shortlisted' THEN 6
        WHEN 'interviewed' THEN 7
        WHEN 'accepted' THEN 8
        WHEN 'rejected' THEN 9
        WHEN 'withdrawn' THEN 10
    END,
    a.submitted_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsByJobParams struct {
	JobID  pgtype.UUID
	Limit  int32
	Offset int32
}

type ListApplicationsByJobRow struct {
	ID                     pgtype.UUID
	JobID                  pgtype.UUID
	UserID                 pgtype.UUID
	GithubUsername         string
	GithubID               int64
	ApplicantEmail         pgtype.Text
	ApplicantName          pgtype.Text
	ApplicantAvatarUrl     pgtype.Text
	CoverLetter            pgtype.Text
	ProposedSalary         pgtype.Int4
	ProposedSalaryCurrency pgtype.Text
	AvailabilityDate       pgtype.Timestamp
	PortfolioUrl           pgtype.Text
	LinkedinUrl            pgtype.Text
	Notes                  pgtype.Text
	Status                 ApplicationStatus
	SubmittedAt            pgtype.Timestamp
	ReviewedAt             pgtype.Timestamp
	ReviewedBy             uuid.UUID
	EmployerFeedback       pgtype.Text
	RejectionReason        pgtype.Text
	QuizID                 uuid.UUID
	QuizScore              pgtype.Int4
	QuizCompletedAt        pgtype.Timestamp
	QuizPassed             pgtype.Bool
	CanViewAiSummary       pgtype.Bool
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	GithubUsername_2       string
	AvatarUrl              pgtype.Text
	Email                  pgtype.Text
	Name                   pgtype.Text
}

func (q *Queries) ListApplicationsByJob(ctx context.Context, arg ListApplicationsByJobParams) ([]ListApplicationsByJobRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByJob, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByJobRow
	for rows.Next() {
		var i ListApplicationsByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GithubUsername_2,
			&i.AvatarUrl,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByStatus = `-- name: ListApplicationsByStatus :many
SELECT id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at FROM job_applications
WHERE status = $1
ORDER BY submitted_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsByStatusParams struct {
	Status ApplicationStatus
	Limit  int32
	Offset int32
}

func (q *Queries) ListApplicationsByStatus(ctx context.Context, arg ListApplicationsByStatusParams) ([]JobApplication, error) {
	rows, err := q.db.Query(ctx, listApplicationsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByUser = `-- name: ListApplicationsByUser :many
SELECT 
    a.id, a.job_id, a.user_id, a.github_username, a.github_id, a.applicant_email, a.applicant_name, a.applicant_avatar_url, a.cover_letter, a.proposed_salary, a.proposed_salary_currency, a.availability_date, a.portfolio_url, a.linkedin_url, a.notes, a.status, a.submitted_at, a.reviewed_at, a.reviewed_by, a.employer_feedback, a.rejection_reason, a.quiz_id, a.quiz_score, a.quiz_completed_at, a.quiz_passed, a.can_view_ai_summary, a.created_at, a.updated_at,
    j.title as job_title,
    j.company as job_company,
    j.status as job_status,
    COALESCE(
        (SELECT json_agg(json_build_object(
            'id', c.id,
            'file_name', c.file_name,
            'version', c.version,
            'uploaded_at', c.uploaded_at
        ))
        FROM cv_application_usage cu
        JOIN cv_versions c ON cu.cv_id = c.id
        WHERE cu.application_id = a.id),
        '[]'::json
    ) as cvs
FROM job_applications a
JOIN jobs j ON a.job_id = j.id
WHERE a.user_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListApplicationsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListApplicationsByUserRow struct {
	ID                     pgtype.UUID
	JobID                  pgtype.UUID
	UserID                 pgtype.UUID
	GithubUsername         string
	GithubID               int64
	ApplicantEmail         pgtype.Text
	ApplicantName          pgtype.Text
	ApplicantAvatarUrl     pgtype.Text
	CoverLetter            pgtype.Text
	ProposedSalary         pgtype.Int4
	ProposedSalaryCurrency pgtype.Text
	AvailabilityDate       pgtype.Timestamp
	PortfolioUrl           pgtype.Text
	LinkedinUrl            pgtype.Text
	Notes                  pgtype.Text
	Status                 ApplicationStatus
	SubmittedAt            pgtype.Timestamp
	ReviewedAt             pgtype.Timestamp
	ReviewedBy             uuid.UUID
	EmployerFeedback       pgtype.Text
	RejectionReason        pgtype.Text
	QuizID                 uuid.UUID
	QuizScore              pgtype.Int4
	QuizCompletedAt        pgtype.Timestamp
	QuizPassed             pgtype.Bool
	CanViewAiSummary       pgtype.Bool
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	JobTitle               string
	JobCompany             string
	JobStatus              JobStatus
	Cvs                    interface{}
}

func (q *Queries) ListApplicationsByUser(ctx context.Context, arg ListApplicationsByUserParams) ([]ListApplicationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByUserRow
	for rows.Next() {
		var i ListApplicationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.JobCompany,
			&i.JobStatus,
			&i.Cvs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInterviewed = `-- name: MarkInterviewed :one
UPDATE job_applications
SET 
    status = 'interviewed',
    updated_at = NOW()
WHERE id = $1 AND status = 'shortlisted'
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

func (q *Queries) MarkInterviewed(ctx context.Context, id pgtype.UUID) (JobApplication, error) {
	row := q.db.QueryRow(ctx, markInterviewed, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectApplication = `-- name: RejectApplication :one
UPDATE job_applications
SET 
    status = 'rejected',
    rejection_reason = $2,
    employer_feedback = $3,
    updated_at = NOW()
WHERE id = $1 AND status NOT IN ('accepted', 'withdrawn')
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type RejectApplicationParams struct {
	ID               pgtype.UUID
	RejectionReason  pgtype.Text
	EmployerFeedback pgtype.Text
}

func (q *Queries) RejectApplication(ctx context.Context, arg RejectApplicationParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, rejectApplication, arg.ID, arg.RejectionReason, arg.EmployerFeedback)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shortlistApplication = `-- name: ShortlistApplication :one
UPDATE job_applications
SET 
    status = 'shortlisted',
    updated_at = NOW()
WHERE id = $1 AND status = 'under_review'
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

func (q *Queries) ShortlistApplication(ctx context.Context, id pgtype.UUID) (JobApplication, error) {
	row := q.db.QueryRow(ctx, shortlistApplication, id)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startReview = `-- name: StartReview :one
UPDATE job_applications
SET 
    status = 'under_review',
    reviewed_at = NOW(),
    reviewed_by = $2,
    updated_at = NOW()
WHERE id = $1 AND status IN ('submitted', 'quiz_completed')
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type StartReviewParams struct {
	ID         pgtype.UUID
	ReviewedBy uuid.UUID
}

func (q *Queries) StartReview(ctx context.Context, arg StartReviewParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, startReview, arg.ID, arg.ReviewedBy)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitApplication = `-- name: SubmitApplication :one

UPDATE job_applications
SET 
    status = 'submitted',
    submitted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status = 'draft'
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type SubmitApplicationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Application Status Updates (Lifecycle)
func (q *Queries) SubmitApplication(ctx context.Context, arg SubmitApplicationParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, submitApplication, arg.ID, arg.UserID)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuizScore = `-- name: UpdateQuizScore :one
UPDATE job_applications
SET 
    quiz_score = $2,
    quiz_passed = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type UpdateQuizScoreParams struct {
	ID         pgtype.UUID
	QuizScore  pgtype.Int4
	QuizPassed pgtype.Bool
}

func (q *Queries) UpdateQuizScore(ctx context.Context, arg UpdateQuizScoreParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, updateQuizScore, arg.ID, arg.QuizScore, arg.QuizPassed)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawApplication = `-- name: WithdrawApplication :one
UPDATE job_applications
SET 
    status = 'withdrawn',
    updated_at = NOW()
WHERE id = $1 AND user_id = $2 AND status NOT IN ('accepted', 'rejected')
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type WithdrawApplicationParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) WithdrawApplication(ctx context.Context, arg WithdrawApplicationParams) (JobApplication, error) {
	row := q.db.QueryRow(ctx, withdrawApplication, arg.ID, arg.UserID)
	var i JobApplication
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.UserID,
		&i.GithubUsername,
		&i.GithubID,
		&i.ApplicantEmail,
		&i.ApplicantName,
		&i.ApplicantAvatarUrl,
		&i.CoverLetter,
		&i.ProposedSalary,
		&i.ProposedSalaryCurrency,
		&i.AvailabilityDate,
		&i.PortfolioUrl,
		&i.LinkedinUrl,
		&i.Notes,
		&i.Status,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.EmployerFeedback,
		&i.RejectionReason,
		&i.QuizID,
		&i.QuizScore,
		&i.QuizCompletedAt,
		&i.QuizPassed,
		&i.CanViewAiSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
