// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package database

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAuditTrail = `-- name: CreateAdminAuditTrail :one

INSERT INTO admin_audit_trail (
    audit_log_id, admin_id, admin_notes,
    approval_required, approved_by, approved_at,
    sensitivity_level
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, audit_log_id, admin_id, admin_notes, approval_required, approved_by, approved_at, sensitivity_level, created_at
`

type CreateAdminAuditTrailParams struct {
	AuditLogID       pgtype.UUID
	AdminID          pgtype.UUID
	AdminNotes       pgtype.Text
	ApprovalRequired pgtype.Bool
	ApprovedBy       uuid.UUID
	ApprovedAt       pgtype.Timestamp
	SensitivityLevel pgtype.Text
}

// Admin audit trail
func (q *Queries) CreateAdminAuditTrail(ctx context.Context, arg CreateAdminAuditTrailParams) (AdminAuditTrail, error) {
	row := q.db.QueryRow(ctx, createAdminAuditTrail,
		arg.AuditLogID,
		arg.AdminID,
		arg.AdminNotes,
		arg.ApprovalRequired,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.SensitivityLevel,
	)
	var i AdminAuditTrail
	err := row.Scan(
		&i.ID,
		&i.AuditLogID,
		&i.AdminID,
		&i.AdminNotes,
		&i.ApprovalRequired,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.SensitivityLevel,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditExport = `-- name: CreateAuditExport :one
INSERT INTO audit_exports (
    exported_by, export_type, date_range_start,
    date_range_end, filter_criteria, file_path
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, exported_by, export_type, date_range_start, date_range_end, filter_criteria, file_path, exported_at, downloaded_count
`

type CreateAuditExportParams struct {
	ExportedBy     uuid.UUID
	ExportType     pgtype.Text
	DateRangeStart pgtype.Timestamp
	DateRangeEnd   pgtype.Timestamp
	FilterCriteria []byte
	FilePath       pgtype.Text
}

func (q *Queries) CreateAuditExport(ctx context.Context, arg CreateAuditExportParams) (AuditExport, error) {
	row := q.db.QueryRow(ctx, createAuditExport,
		arg.ExportedBy,
		arg.ExportType,
		arg.DateRangeStart,
		arg.DateRangeEnd,
		arg.FilterCriteria,
		arg.FilePath,
	)
	var i AuditExport
	err := row.Scan(
		&i.ID,
		&i.ExportedBy,
		&i.ExportType,
		&i.DateRangeStart,
		&i.DateRangeEnd,
		&i.FilterCriteria,
		&i.FilePath,
		&i.ExportedAt,
		&i.DownloadedCount,
	)
	return i, err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO audit_logs (
    user_id, user_email, user_role, action,
    entity_type, entity_id, ip_address, user_agent,
    details, old_values, new_values, status, error_message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion
`

type CreateAuditLogParams struct {
	UserID       uuid.UUID
	UserEmail    pgtype.Text
	UserRole     pgtype.Text
	Action       AuditAction
	EntityType   pgtype.Text
	EntityID     uuid.UUID
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	Details      []byte
	OldValues    []byte
	NewValues    []byte
	Status       pgtype.Text
	ErrorMessage pgtype.Text
}

// Create audit log entry
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.UserEmail,
		arg.UserRole,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Details,
		arg.OldValues,
		arg.NewValues,
		arg.Status,
		arg.ErrorMessage,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserRole,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.PerformedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Details,
		&i.OldValues,
		&i.NewValues,
		&i.Status,
		&i.ErrorMessage,
		&i.DataRetentionDays,
		&i.MarkedForDeletion,
	)
	return i, err
}

const deleteMarkedLogs = `-- name: DeleteMarkedLogs :exec

DELETE FROM audit_logs
WHERE marked_for_deletion = true
AND performed_at < NOW() - interval '30 days'
`

// Cleanup
func (q *Queries) DeleteMarkedLogs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteMarkedLogs)
	return err
}

const deleteOldLogs = `-- name: DeleteOldLogs :exec
DELETE FROM audit_logs
WHERE performed_at < NOW() - interval '1 year'
`

func (q *Queries) DeleteOldLogs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldLogs)
	return err
}

const getAdminActions = `-- name: GetAdminActions :many
SELECT 
    a.id, a.user_id, a.user_email, a.user_role, a.action, a.entity_type, a.entity_id, a.performed_at, a.ip_address, a.user_agent, a.details, a.old_values, a.new_values, a.status, a.error_message, a.data_retention_days, a.marked_for_deletion,
    at.admin_notes,
    at.sensitivity_level,
    at.approval_required,
    at.approved_at
FROM audit_logs a
JOIN admin_audit_trail at ON a.id = at.audit_log_id
WHERE a.performed_at BETWEEN $1 AND $2
ORDER BY a.performed_at DESC
LIMIT $3 OFFSET $4
`

type GetAdminActionsParams struct {
	PerformedAt   pgtype.Timestamp
	PerformedAt_2 pgtype.Timestamp
	Limit         int32
	Offset        int32
}

type GetAdminActionsRow struct {
	ID                pgtype.UUID
	UserID            uuid.UUID
	UserEmail         pgtype.Text
	UserRole          pgtype.Text
	Action            AuditAction
	EntityType        pgtype.Text
	EntityID          uuid.UUID
	PerformedAt       pgtype.Timestamp
	IpAddress         *netip.Addr
	UserAgent         pgtype.Text
	Details           []byte
	OldValues         []byte
	NewValues         []byte
	Status            pgtype.Text
	ErrorMessage      pgtype.Text
	DataRetentionDays pgtype.Int4
	MarkedForDeletion pgtype.Bool
	AdminNotes        pgtype.Text
	SensitivityLevel  pgtype.Text
	ApprovalRequired  pgtype.Bool
	ApprovedAt        pgtype.Timestamp
}

func (q *Queries) GetAdminActions(ctx context.Context, arg GetAdminActionsParams) ([]GetAdminActionsRow, error) {
	rows, err := q.db.Query(ctx, getAdminActions,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminActionsRow
	for rows.Next() {
		var i GetAdminActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
			&i.AdminNotes,
			&i.SensitivityLevel,
			&i.ApprovalRequired,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditLogByID = `-- name: GetAuditLogByID :one

SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs WHERE id = $1
`

// Query audit logs
func (q *Queries) GetAuditLogByID(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogByID, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserEmail,
		&i.UserRole,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.PerformedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Details,
		&i.OldValues,
		&i.NewValues,
		&i.Status,
		&i.ErrorMessage,
		&i.DataRetentionDays,
		&i.MarkedForDeletion,
	)
	return i, err
}

const getAuditStats = `-- name: GetAuditStats :many

SELECT 
    DATE(performed_at) as date,
    action,
    COUNT(*) as count
FROM audit_logs
WHERE performed_at BETWEEN $1 AND $2
GROUP BY DATE(performed_at), action
ORDER BY date DESC
`

type GetAuditStatsParams struct {
	PerformedAt   pgtype.Timestamp
	PerformedAt_2 pgtype.Timestamp
}

type GetAuditStatsRow struct {
	Date   pgtype.Date
	Action AuditAction
	Count  int64
}

// Statistics
func (q *Queries) GetAuditStats(ctx context.Context, arg GetAuditStatsParams) ([]GetAuditStatsRow, error) {
	rows, err := q.db.Query(ctx, getAuditStats, arg.PerformedAt, arg.PerformedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditStatsRow
	for rows.Next() {
		var i GetAuditStatsRow
		if err := rows.Scan(&i.Date, &i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityHistory = `-- name: GetEntityHistory :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY performed_at
`

type GetEntityHistoryParams struct {
	EntityType pgtype.Text
	EntityID   uuid.UUID
}

func (q *Queries) GetEntityHistory(ctx context.Context, arg GetEntityHistoryParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getEntityHistory, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLogsForExport = `-- name: GetLogsForExport :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE performed_at BETWEEN $1 AND $2
AND (user_id = $3 OR $3 IS NULL)
ORDER BY performed_at
`

type GetLogsForExportParams struct {
	PerformedAt   pgtype.Timestamp
	PerformedAt_2 pgtype.Timestamp
	UserID        uuid.UUID
}

func (q *Queries) GetLogsForExport(ctx context.Context, arg GetLogsForExportParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getLogsForExport, arg.PerformedAt, arg.PerformedAt_2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingApprovals = `-- name: GetPendingApprovals :many
SELECT id, audit_log_id, admin_id, admin_notes, approval_required, approved_by, approved_at, sensitivity_level, created_at FROM admin_audit_trail
WHERE approval_required = true AND approved_at IS NULL
ORDER BY created_at
`

func (q *Queries) GetPendingApprovals(ctx context.Context) ([]AdminAuditTrail, error) {
	rows, err := q.db.Query(ctx, getPendingApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditTrail
	for rows.Next() {
		var i AdminAuditTrail
		if err := rows.Scan(
			&i.ID,
			&i.AuditLogID,
			&i.AdminID,
			&i.AdminNotes,
			&i.ApprovalRequired,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.SensitivityLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserActivitySummary = `-- name: GetUserActivitySummary :one
SELECT 
    COUNT(*) as total_actions,
    COUNT(DISTINCT DATE(performed_at)) as active_days,
    MAX(performed_at) as last_active,
    MIN(performed_at) as first_active
FROM audit_logs
WHERE user_id = $1
`

type GetUserActivitySummaryRow struct {
	TotalActions int64
	ActiveDays   int64
	LastActive   interface{}
	FirstActive  interface{}
}

func (q *Queries) GetUserActivitySummary(ctx context.Context, userID uuid.UUID) (GetUserActivitySummaryRow, error) {
	row := q.db.QueryRow(ctx, getUserActivitySummary, userID)
	var i GetUserActivitySummaryRow
	err := row.Scan(
		&i.TotalActions,
		&i.ActiveDays,
		&i.LastActive,
		&i.FirstActive,
	)
	return i, err
}

const getUserAuditTrail = `-- name: GetUserAuditTrail :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE user_id = $1
AND performed_at > NOW() - interval '90 days'
ORDER BY performed_at DESC
`

func (q *Queries) GetUserAuditTrail(ctx context.Context, userID uuid.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getUserAuditTrail, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementExportDownload = `-- name: IncrementExportDownload :exec
UPDATE audit_exports
SET downloaded_count = downloaded_count + 1
WHERE id = $1
`

func (q *Queries) IncrementExportDownload(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementExportDownload, id)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE performed_at BETWEEN $1 AND $2
ORDER BY performed_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsParams struct {
	PerformedAt   pgtype.Timestamp
	PerformedAt_2 pgtype.Timestamp
	Limit         int32
	Offset        int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.PerformedAt,
		arg.PerformedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE action = $1
ORDER BY performed_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByActionParams struct {
	Action AuditAction
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAction, arg.Action, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByEntity = `-- name: ListAuditLogsByEntity :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY performed_at DESC
`

type ListAuditLogsByEntityParams struct {
	EntityType pgtype.Text
	EntityID   uuid.UUID
}

func (q *Queries) ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByIP = `-- name: ListAuditLogsByIP :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE ip_address = $1
ORDER BY performed_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByIPParams struct {
	IpAddress *netip.Addr
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAuditLogsByIP(ctx context.Context, arg ListAuditLogsByIPParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByIP, arg.IpAddress, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, user_id, user_email, user_role, action, entity_type, entity_id, performed_at, ip_address, user_agent, details, old_values, new_values, status, error_message, data_retention_days, marked_for_deletion FROM audit_logs
WHERE user_id = $1
ORDER BY performed_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserRole,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.PerformedAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.OldValues,
			&i.NewValues,
			&i.Status,
			&i.ErrorMessage,
			&i.DataRetentionDays,
			&i.MarkedForDeletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markForDeletion = `-- name: MarkForDeletion :exec

UPDATE audit_logs
SET marked_for_deletion = true
WHERE performed_at < NOW() - (interval '1 day' * data_retention_days)
`

// Compliance and GDPR
func (q *Queries) MarkForDeletion(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markForDeletion)
	return err
}
