// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch_operations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOldApplications = `-- name: ArchiveOldApplications :many
UPDATE job_applications
SET 
    status = 'withdrawn',
    updated_at = NOW()
WHERE submitted_at < NOW() - interval '6 months'
AND status IN ('submitted', 'quiz_started', 'quiz_completed')
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

func (q *Queries) ArchiveOldApplications(ctx context.Context) ([]JobApplication, error) {
	rows, err := q.db.Query(ctx, archiveOldApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bulkUpdateApplicationStatus = `-- name: BulkUpdateApplicationStatus :many

UPDATE job_applications
SET 
    status = $2,
    updated_at = NOW()
WHERE job_id = $1 AND status = $3
RETURNING id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at
`

type BulkUpdateApplicationStatusParams struct {
	JobID    pgtype.UUID
	Status   ApplicationStatus
	Status_2 ApplicationStatus
}

// Bulk operations for admin/reporting
func (q *Queries) BulkUpdateApplicationStatus(ctx context.Context, arg BulkUpdateApplicationStatusParams) ([]JobApplication, error) {
	rows, err := q.db.Query(ctx, bulkUpdateApplicationStatus, arg.JobID, arg.Status, arg.Status_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cleanupUnusedCVs = `-- name: CleanupUnusedCVs :many
DELETE FROM cv_versions
WHERE id NOT IN (
    SELECT DISTINCT cv_id FROM cv_application_usage
)
AND created_at < NOW() - interval '30 days'
RETURNING id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at
`

func (q *Queries) CleanupUnusedCVs(ctx context.Context) ([]CvVersion, error) {
	rows, err := q.db.Query(ctx, cleanupUnusedCVs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvVersion
	for rows.Next() {
		var i CvVersion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedAt,
			&i.UploadedFromIp,
			&i.ApplicationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationsByDateRange = `-- name: GetApplicationsByDateRange :many
SELECT id, job_id, user_id, github_username, github_id, applicant_email, applicant_name, applicant_avatar_url, cover_letter, proposed_salary, proposed_salary_currency, availability_date, portfolio_url, linkedin_url, notes, status, submitted_at, reviewed_at, reviewed_by, employer_feedback, rejection_reason, quiz_id, quiz_score, quiz_completed_at, quiz_passed, can_view_ai_summary, created_at, updated_at FROM job_applications
WHERE submitted_at BETWEEN $1 AND $2
ORDER BY submitted_at
`

type GetApplicationsByDateRangeParams struct {
	SubmittedAt   pgtype.Timestamp
	SubmittedAt_2 pgtype.Timestamp
}

func (q *Queries) GetApplicationsByDateRange(ctx context.Context, arg GetApplicationsByDateRangeParams) ([]JobApplication, error) {
	rows, err := q.db.Query(ctx, getApplicationsByDateRange, arg.SubmittedAt, arg.SubmittedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobApplication
	for rows.Next() {
		var i JobApplication
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVsByDateRange = `-- name: GetCVsByDateRange :many
SELECT id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at FROM cv_versions
WHERE created_at BETWEEN $1 AND $2
ORDER BY created_at
`

type GetCVsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamp
	CreatedAt_2 pgtype.Timestamp
}

func (q *Queries) GetCVsByDateRange(ctx context.Context, arg GetCVsByDateRangeParams) ([]CvVersion, error) {
	rows, err := q.db.Query(ctx, getCVsByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvVersion
	for rows.Next() {
		var i CvVersion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedAt,
			&i.UploadedFromIp,
			&i.ApplicationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
