// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_settings.sql

package database

import (
	"context"
)

const getCompanySettings = `-- name: GetCompanySettings :one
SELECT id, company_name, company_logo, company_website, company_location, created_at, updated_at FROM company_settings LIMIT 1
`

func (q *Queries) GetCompanySettings(ctx context.Context) (CompanySetting, error) {
	row := q.db.QueryRow(ctx, getCompanySettings)
	var i CompanySetting
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobCountsByCategory = `-- name: GetJobCountsByCategory :many
SELECT category, COUNT(*)::int AS job_count
FROM jobs
GROUP BY category
ORDER BY job_count DESC
`

type GetJobCountsByCategoryRow struct {
	Category JobCategory
	JobCount int32
}

func (q *Queries) GetJobCountsByCategory(ctx context.Context) ([]GetJobCountsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getJobCountsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobCountsByCategoryRow
	for rows.Next() {
		var i GetJobCountsByCategoryRow
		if err := rows.Scan(&i.Category, &i.JobCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanySettings = `-- name: UpdateCompanySettings :one
UPDATE company_settings
SET
    company_name     = $1,
    company_logo     = $2,
    company_website  = $3,
    company_location = $4,
    updated_at       = NOW()
WHERE id = (SELECT id FROM company_settings LIMIT 1)
RETURNING id, company_name, company_logo, company_website, company_location, created_at, updated_at
`

type UpdateCompanySettingsParams struct {
	CompanyName     string
	CompanyLogo     string
	CompanyWebsite  string
	CompanyLocation string
}

func (q *Queries) UpdateCompanySettings(ctx context.Context, arg UpdateCompanySettingsParams) (CompanySetting, error) {
	row := q.db.QueryRow(ctx, updateCompanySettings,
		arg.CompanyName,
		arg.CompanyLogo,
		arg.CompanyWebsite,
		arg.CompanyLocation,
	)
	var i CompanySetting
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
