// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_requests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countContactRequests = `-- name: CountContactRequests :one
SELECT COUNT(*) FROM contact_requests
`

func (q *Queries) CountContactRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countContactRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContactRequest = `-- name: CreateContactRequest :one
INSERT INTO contact_requests (
    first_name, last_name, email, company, budget_range, project_details
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, first_name, last_name, email, company, budget_range, project_details, status, created_at
`

type CreateContactRequestParams struct {
	FirstName      string
	LastName       string
	Email          string
	Company        pgtype.Text
	BudgetRange    pgtype.Text
	ProjectDetails string
}

func (q *Queries) CreateContactRequest(ctx context.Context, arg CreateContactRequestParams) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, createContactRequest,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Company,
		arg.BudgetRange,
		arg.ProjectDetails,
	)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Company,
		&i.BudgetRange,
		&i.ProjectDetails,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContactRequest = `-- name: DeleteContactRequest :exec
DELETE FROM contact_requests
WHERE id = $1
`

func (q *Queries) DeleteContactRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContactRequest, id)
	return err
}

const getContactRequest = `-- name: GetContactRequest :one
SELECT id, first_name, last_name, email, company, budget_range, project_details, status, created_at FROM contact_requests
WHERE id = $1
`

func (q *Queries) GetContactRequest(ctx context.Context, id pgtype.UUID) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, getContactRequest, id)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Company,
		&i.BudgetRange,
		&i.ProjectDetails,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listContactRequests = `-- name: ListContactRequests :many
SELECT id, first_name, last_name, email, company, budget_range, project_details, status, created_at FROM contact_requests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListContactRequestsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListContactRequests(ctx context.Context, arg ListContactRequestsParams) ([]ContactRequest, error) {
	rows, err := q.db.Query(ctx, listContactRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactRequest
	for rows.Next() {
		var i ContactRequest
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Company,
			&i.BudgetRange,
			&i.ProjectDetails,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactRequestsByEmail = `-- name: ListContactRequestsByEmail :many
SELECT id, first_name, last_name, email, company, budget_range, project_details, status, created_at FROM contact_requests
WHERE LOWER(email) = LOWER($1)
ORDER BY created_at DESC
`

func (q *Queries) ListContactRequestsByEmail(ctx context.Context, lower string) ([]ContactRequest, error) {
	rows, err := q.db.Query(ctx, listContactRequestsByEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactRequest
	for rows.Next() {
		var i ContactRequest
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Company,
			&i.BudgetRange,
			&i.ProjectDetails,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactRequestStatus = `-- name: UpdateContactRequestStatus :one
UPDATE contact_requests
SET status = $2
WHERE id = $1
RETURNING id, first_name, last_name, email, company, budget_range, project_details, status, created_at
`

type UpdateContactRequestStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateContactRequestStatus(ctx context.Context, arg UpdateContactRequestStatusParams) (ContactRequest, error) {
	row := q.db.QueryRow(ctx, updateContactRequestStatus, arg.ID, arg.Status)
	var i ContactRequest
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Company,
		&i.BudgetRange,
		&i.ProjectDetails,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
