// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cv_signals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCVSignalsByUser = `-- name: GetCVSignalsByUser :one
SELECT id, user_id, claimed_skills, experience_level, projects_listed, credibility, alignment_with_github, raw_summary, created_at, updated_at FROM cv_signals
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetCVSignalsByUser(ctx context.Context, userID pgtype.UUID) (CvSignal, error) {
	row := q.db.QueryRow(ctx, getCVSignalsByUser, userID)
	var i CvSignal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClaimedSkills,
		&i.ExperienceLevel,
		&i.ProjectsListed,
		&i.Credibility,
		&i.AlignmentWithGithub,
		&i.RawSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCVSignals = `-- name: UpsertCVSignals :one
INSERT INTO cv_signals (
    user_id,
    claimed_skills,
    experience_level,
    projects_listed,
    credibility,
    alignment_with_github,
    raw_summary
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id)
DO UPDATE SET
    claimed_skills = EXCLUDED.claimed_skills,
    experience_level = EXCLUDED.experience_level,
    projects_listed = EXCLUDED.projects_listed,
    credibility = EXCLUDED.credibility,
    alignment_with_github = EXCLUDED.alignment_with_github,
    raw_summary = EXCLUDED.raw_summary,
    updated_at = NOW()
RETURNING id, user_id, claimed_skills, experience_level, projects_listed, credibility, alignment_with_github, raw_summary, created_at, updated_at
`

type UpsertCVSignalsParams struct {
	UserID              pgtype.UUID
	ClaimedSkills       []byte
	ExperienceLevel     pgtype.Text
	ProjectsListed      pgtype.Int4
	Credibility         pgtype.Text
	AlignmentWithGithub pgtype.Text
	RawSummary          pgtype.Text
}

func (q *Queries) UpsertCVSignals(ctx context.Context, arg UpsertCVSignalsParams) (CvSignal, error) {
	row := q.db.QueryRow(ctx, upsertCVSignals,
		arg.UserID,
		arg.ClaimedSkills,
		arg.ExperienceLevel,
		arg.ProjectsListed,
		arg.Credibility,
		arg.AlignmentWithGithub,
		arg.RawSummary,
	)
	var i CvSignal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClaimedSkills,
		&i.ExperienceLevel,
		&i.ProjectsListed,
		&i.Credibility,
		&i.AlignmentWithGithub,
		&i.RawSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
