// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cv_usage.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCVUsage = `-- name: CountCVUsage :one
SELECT COUNT(*) FROM cv_application_usage
WHERE cv_id = $1
`

func (q *Queries) CountCVUsage(ctx context.Context, cvID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCVUsage, cvID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApplicationsByCV = `-- name: GetApplicationsByCV :many
SELECT 
    a.id, a.job_id, a.user_id, a.github_username, a.github_id, a.applicant_email, a.applicant_name, a.applicant_avatar_url, a.cover_letter, a.proposed_salary, a.proposed_salary_currency, a.availability_date, a.portfolio_url, a.linkedin_url, a.notes, a.status, a.submitted_at, a.reviewed_at, a.reviewed_by, a.employer_feedback, a.rejection_reason, a.quiz_id, a.quiz_score, a.quiz_completed_at, a.quiz_passed, a.can_view_ai_summary, a.created_at, a.updated_at,
    j.title,
    j.company
FROM cv_application_usage cu
JOIN job_applications a ON cu.application_id = a.id
JOIN jobs j ON a.job_id = j.id
WHERE cu.cv_id = $1
ORDER BY cu.used_at DESC
`

type GetApplicationsByCVRow struct {
	ID                     pgtype.UUID
	JobID                  pgtype.UUID
	UserID                 pgtype.UUID
	GithubUsername         string
	GithubID               int64
	ApplicantEmail         pgtype.Text
	ApplicantName          pgtype.Text
	ApplicantAvatarUrl     pgtype.Text
	CoverLetter            pgtype.Text
	ProposedSalary         pgtype.Int4
	ProposedSalaryCurrency pgtype.Text
	AvailabilityDate       pgtype.Timestamp
	PortfolioUrl           pgtype.Text
	LinkedinUrl            pgtype.Text
	Notes                  pgtype.Text
	Status                 ApplicationStatus
	SubmittedAt            pgtype.Timestamp
	ReviewedAt             pgtype.Timestamp
	ReviewedBy             uuid.UUID
	EmployerFeedback       pgtype.Text
	RejectionReason        pgtype.Text
	QuizID                 uuid.UUID
	QuizScore              pgtype.Int4
	QuizCompletedAt        pgtype.Timestamp
	QuizPassed             pgtype.Bool
	CanViewAiSummary       pgtype.Bool
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	Title                  string
	Company                string
}

func (q *Queries) GetApplicationsByCV(ctx context.Context, cvID pgtype.UUID) ([]GetApplicationsByCVRow, error) {
	rows, err := q.db.Query(ctx, getApplicationsByCV, cvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApplicationsByCVRow
	for rows.Next() {
		var i GetApplicationsByCVRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.UserID,
			&i.GithubUsername,
			&i.GithubID,
			&i.ApplicantEmail,
			&i.ApplicantName,
			&i.ApplicantAvatarUrl,
			&i.CoverLetter,
			&i.ProposedSalary,
			&i.ProposedSalaryCurrency,
			&i.AvailabilityDate,
			&i.PortfolioUrl,
			&i.LinkedinUrl,
			&i.Notes,
			&i.Status,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.EmployerFeedback,
			&i.RejectionReason,
			&i.QuizID,
			&i.QuizScore,
			&i.QuizCompletedAt,
			&i.QuizPassed,
			&i.CanViewAiSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Company,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationsUsingCV = `-- name: GetApplicationsUsingCV :many
SELECT DISTINCT application_id
FROM cv_application_usage
WHERE cv_id = $1
`

func (q *Queries) GetApplicationsUsingCV(ctx context.Context, cvID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getApplicationsUsingCV, cvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var application_id pgtype.UUID
		if err := rows.Scan(&application_id); err != nil {
			return nil, err
		}
		items = append(items, application_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVUsageHistory = `-- name: GetCVUsageHistory :many
SELECT 
    cu.cv_id, cu.application_id, cu.used_at,
    a.status as application_status,
    j.title as job_title,
    j.company as job_company
FROM cv_application_usage cu
JOIN job_applications a ON cu.application_id = a.id
JOIN jobs j ON a.job_id = j.id
WHERE cu.cv_id = $1
ORDER BY cu.used_at DESC
`

type GetCVUsageHistoryRow struct {
	CvID              pgtype.UUID
	ApplicationID     pgtype.UUID
	UsedAt            pgtype.Timestamp
	ApplicationStatus ApplicationStatus
	JobTitle          string
	JobCompany        string
}

func (q *Queries) GetCVUsageHistory(ctx context.Context, cvID pgtype.UUID) ([]GetCVUsageHistoryRow, error) {
	rows, err := q.db.Query(ctx, getCVUsageHistory, cvID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCVUsageHistoryRow
	for rows.Next() {
		var i GetCVUsageHistoryRow
		if err := rows.Scan(
			&i.CvID,
			&i.ApplicationID,
			&i.UsedAt,
			&i.ApplicationStatus,
			&i.JobTitle,
			&i.JobCompany,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVsForApplication = `-- name: GetCVsForApplication :many
SELECT c.id, c.user_id, c.file_name, c.file_path, c.file_size, c.file_hash, c.version, c.is_current, c.uploaded_at, c.uploaded_from_ip, c.application_id, c.created_at
FROM cv_application_usage cu
JOIN cv_versions c ON cu.cv_id = c.id
WHERE cu.application_id = $1
ORDER BY cu.used_at DESC
`

func (q *Queries) GetCVsForApplication(ctx context.Context, applicationID pgtype.UUID) ([]CvVersion, error) {
	rows, err := q.db.Query(ctx, getCVsForApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvVersion
	for rows.Next() {
		var i CvVersion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedAt,
			&i.UploadedFromIp,
			&i.ApplicationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCVForApplication = `-- name: GetLatestCVForApplication :one
SELECT c.id, c.user_id, c.file_name, c.file_path, c.file_size, c.file_hash, c.version, c.is_current, c.uploaded_at, c.uploaded_from_ip, c.application_id, c.created_at
FROM cv_application_usage cu
JOIN cv_versions c ON cu.cv_id = c.id
WHERE cu.application_id = $1
ORDER BY cu.used_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCVForApplication(ctx context.Context, applicationID pgtype.UUID) (CvVersion, error) {
	row := q.db.QueryRow(ctx, getLatestCVForApplication, applicationID)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
	)
	return i, err
}

const linkCVToApplication = `-- name: LinkCVToApplication :exec

INSERT INTO cv_application_usage (cv_id, application_id)
VALUES ($1, $2)
ON CONFLICT (cv_id, application_id) DO NOTHING
`

type LinkCVToApplicationParams struct {
	CvID          pgtype.UUID
	ApplicationID pgtype.UUID
}

// Track which CVs are used for which applications
func (q *Queries) LinkCVToApplication(ctx context.Context, arg LinkCVToApplicationParams) error {
	_, err := q.db.Exec(ctx, linkCVToApplication, arg.CvID, arg.ApplicationID)
	return err
}

const removeCVFromAllApplications = `-- name: RemoveCVFromAllApplications :exec
DELETE FROM cv_application_usage
WHERE cv_id = $1
`

func (q *Queries) RemoveCVFromAllApplications(ctx context.Context, cvID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeCVFromAllApplications, cvID)
	return err
}

const transferCVUsage = `-- name: TransferCVUsage :exec
UPDATE cv_application_usage
SET cv_id = $2
WHERE cv_id = $1
`

type TransferCVUsageParams struct {
	CvID   pgtype.UUID
	CvID_2 pgtype.UUID
}

func (q *Queries) TransferCVUsage(ctx context.Context, arg TransferCVUsageParams) error {
	_, err := q.db.Exec(ctx, transferCVUsage, arg.CvID, arg.CvID_2)
	return err
}

const unlinkCVFromApplication = `-- name: UnlinkCVFromApplication :exec
DELETE FROM cv_application_usage
WHERE cv_id = $1 AND application_id = $2
`

type UnlinkCVFromApplicationParams struct {
	CvID          pgtype.UUID
	ApplicationID pgtype.UUID
}

func (q *Queries) UnlinkCVFromApplication(ctx context.Context, arg UnlinkCVFromApplicationParams) error {
	_, err := q.db.Exec(ctx, unlinkCVFromApplication, arg.CvID, arg.ApplicationID)
	return err
}
