// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cv_versions.sql

package database

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUserCVs = `-- name: CountUserCVs :one
SELECT COUNT(*) FROM cv_versions
WHERE user_id = $1
`

func (q *Queries) CountUserCVs(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCVs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCV = `-- name: CreateCV :one

INSERT INTO cv_versions (
    user_id, file_name, file_path, file_size, 
    file_hash, version, is_current, uploaded_from_ip,
    application_id
) VALUES (
    $1, $2, $3, $4, $5, 
    COALESCE((SELECT MAX(version) + 1 FROM cv_versions WHERE user_id = $1), 1),
    true, $6, NULLIF($7, '00000000-0000-0000-0000-000000000000'::uuid)
) RETURNING id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at
`

type CreateCVParams struct {
	UserID         pgtype.UUID
	FileName       string
	FilePath       string
	FileSize       int32
	FileHash       string
	UploadedFromIp *netip.Addr
	Column7        interface{}
}

// CV CRUD operations
func (q *Queries) CreateCV(ctx context.Context, arg CreateCVParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, createCV,
		arg.UserID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.FileHash,
		arg.UploadedFromIp,
		arg.Column7,
	)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCV = `-- name: DeleteCV :exec
DELETE FROM cv_versions
WHERE id = $1 AND user_id = $2
`

type DeleteCVParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteCV(ctx context.Context, arg DeleteCVParams) error {
	_, err := q.db.Exec(ctx, deleteCV, arg.ID, arg.UserID)
	return err
}

const deleteOldCVs = `-- name: DeleteOldCVs :exec
DELETE FROM cv_versions c
WHERE c.user_id = $1
AND c.id NOT IN (
    SELECT id FROM cv_versions
    WHERE user_id = $1
    ORDER BY version DESC
    LIMIT 5  -- Keep last 5 versions
)
`

func (q *Queries) DeleteOldCVs(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOldCVs, userID)
	return err
}

const findDuplicateCV = `-- name: FindDuplicateCV :one
SELECT id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at FROM cv_versions
WHERE user_id = $1 AND file_hash = $2
LIMIT 1
`

type FindDuplicateCVParams struct {
	UserID   pgtype.UUID
	FileHash string
}

func (q *Queries) FindDuplicateCV(ctx context.Context, arg FindDuplicateCVParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, findDuplicateCV, arg.UserID, arg.FileHash)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVByHash = `-- name: GetCVByHash :one
SELECT id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at FROM cv_versions 
WHERE user_id = $1 AND file_hash = $2 
ORDER BY version DESC LIMIT 1
`

type GetCVByHashParams struct {
	UserID   pgtype.UUID
	FileHash string
}

func (q *Queries) GetCVByHash(ctx context.Context, arg GetCVByHashParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, getCVByHash, arg.UserID, arg.FileHash)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVByID = `-- name: GetCVByID :one
SELECT id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at FROM cv_versions WHERE id = $1
`

func (q *Queries) GetCVByID(ctx context.Context, id pgtype.UUID) (CvVersion, error) {
	row := q.db.QueryRow(ctx, getCVByID, id)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVStats = `-- name: GetCVStats :one
SELECT 
    COUNT(*) as total_cvs,
    SUM(file_size) as total_storage_bytes,
    MAX(version) as latest_version,
    COUNT(DISTINCT application_id) as applications_used
FROM cv_versions
WHERE user_id = $1
`

type GetCVStatsRow struct {
	TotalCvs          int64
	TotalStorageBytes int64
	LatestVersion     interface{}
	ApplicationsUsed  int64
}

func (q *Queries) GetCVStats(ctx context.Context, userID pgtype.UUID) (GetCVStatsRow, error) {
	row := q.db.QueryRow(ctx, getCVStats, userID)
	var i GetCVStatsRow
	err := row.Scan(
		&i.TotalCvs,
		&i.TotalStorageBytes,
		&i.LatestVersion,
		&i.ApplicationsUsed,
	)
	return i, err
}

const getCVVersions = `-- name: GetCVVersions :many
SELECT 
    version,
    file_name,
    file_size,
    created_at,
    is_current,
    application_id
FROM cv_versions
WHERE user_id = $1
ORDER BY version DESC
`

type GetCVVersionsRow struct {
	Version       int32
	FileName      string
	FileSize      int32
	CreatedAt     pgtype.Timestamp
	IsCurrent     pgtype.Bool
	ApplicationID uuid.UUID
}

func (q *Queries) GetCVVersions(ctx context.Context, userID pgtype.UUID) ([]GetCVVersionsRow, error) {
	rows, err := q.db.Query(ctx, getCVVersions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCVVersionsRow
	for rows.Next() {
		var i GetCVVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.FileName,
			&i.FileSize,
			&i.CreatedAt,
			&i.IsCurrent,
			&i.ApplicationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVsByApplication = `-- name: GetCVsByApplication :many
SELECT 
    c.id, c.user_id, c.file_name, c.file_path, c.file_size, c.file_hash, c.version, c.is_current, c.uploaded_at, c.uploaded_from_ip, c.application_id, c.created_at, c.updated_at,
    cu.used_at
FROM cv_versions c
JOIN cv_application_usage cu ON c.id = cu.cv_id
WHERE cu.application_id = $1
ORDER BY cu.used_at DESC
`

type GetCVsByApplicationRow struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	FileName       string
	FilePath       string
	FileSize       int32
	FileHash       string
	Version        int32
	IsCurrent      pgtype.Bool
	UploadedAt     pgtype.Timestamp
	UploadedFromIp *netip.Addr
	ApplicationID  uuid.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	UsedAt         pgtype.Timestamp
}

func (q *Queries) GetCVsByApplication(ctx context.Context, applicationID pgtype.UUID) ([]GetCVsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, getCVsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCVsByApplicationRow
	for rows.Next() {
		var i GetCVsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedAt,
			&i.UploadedFromIp,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentCV = `-- name: GetCurrentCV :one
SELECT id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at FROM cv_versions
WHERE user_id = $1 AND is_current = true
LIMIT 1
`

func (q *Queries) GetCurrentCV(ctx context.Context, userID pgtype.UUID) (CvVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentCV, userID)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCVsByUser = `-- name: ListCVsByUser :many
SELECT id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at FROM cv_versions
WHERE user_id = $1
ORDER BY 
    is_current DESC,
    version DESC,
    created_at DESC
LIMIT $2 OFFSET $3
`

type ListCVsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListCVsByUser(ctx context.Context, arg ListCVsByUserParams) ([]CvVersion, error) {
	rows, err := q.db.Query(ctx, listCVsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CvVersion
	for rows.Next() {
		var i CvVersion
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.FileHash,
			&i.Version,
			&i.IsCurrent,
			&i.UploadedAt,
			&i.UploadedFromIp,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCVAsCurrent = `-- name: MarkCVAsCurrent :exec
UPDATE cv_versions
SET is_current = true, updated_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkCVAsCurrentParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) MarkCVAsCurrent(ctx context.Context, arg MarkCVAsCurrentParams) error {
	_, err := q.db.Exec(ctx, markCVAsCurrent, arg.ID, arg.UserID)
	return err
}

const setCurrentCV = `-- name: SetCurrentCV :exec
UPDATE cv_versions
SET is_current = false
WHERE user_id = $1 AND is_current = true
`

func (q *Queries) SetCurrentCV(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setCurrentCV, userID)
	return err
}

const updateCV = `-- name: UpdateCV :one
UPDATE cv_versions
SET 
    file_name = $2,
    file_path = $3,
    file_size = $4,
    file_hash = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, file_name, file_path, file_size, file_hash, version, is_current, uploaded_at, uploaded_from_ip, application_id, created_at, updated_at
`

type UpdateCVParams struct {
	ID       pgtype.UUID
	FileName string
	FilePath string
	FileSize int32
	FileHash string
}

func (q *Queries) UpdateCV(ctx context.Context, arg UpdateCVParams) (CvVersion, error) {
	row := q.db.QueryRow(ctx, updateCV,
		arg.ID,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.FileHash,
	)
	var i CvVersion
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.FileHash,
		&i.Version,
		&i.IsCurrent,
		&i.UploadedAt,
		&i.UploadedFromIp,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
