// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: developer_field.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateUserWithProfile = `-- name: CreateOrUpdateUserWithProfile :one
INSERT INTO users (
    github_id, 
    github_username, 
    email, 
    avatar_url, 
    name, 
    github_access_token, 
    github_token_expires_at,
    last_login_at,
    public_repos,
    public_gists,
    followers,
    following,
    hireable,
    blog,
    company,
    location,
    bio,
    twitter_username,
    top_languages,
    contribution_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
ON CONFLICT (github_id) 
DO UPDATE SET 
    github_username = EXCLUDED.github_username,
    email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    name = EXCLUDED.name,
    github_access_token = EXCLUDED.github_access_token,
    github_token_expires_at = EXCLUDED.github_token_expires_at,
    last_login_at = NOW(),
    updated_at = NOW(),
    public_repos = EXCLUDED.public_repos,
    public_gists = EXCLUDED.public_gists,
    followers = EXCLUDED.followers,
    following = EXCLUDED.following,
    hireable = EXCLUDED.hireable,
    blog = EXCLUDED.blog,
    company = EXCLUDED.company,
    location = EXCLUDED.location,
    bio = EXCLUDED.bio,
    twitter_username = EXCLUDED.twitter_username,
    top_languages = EXCLUDED.top_languages,
    contribution_count = EXCLUDED.contribution_count
RETURNING id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count
`

type CreateOrUpdateUserWithProfileParams struct {
	GithubID             int64
	GithubUsername       string
	Email                pgtype.Text
	AvatarUrl            pgtype.Text
	Name                 pgtype.Text
	GithubAccessToken    pgtype.Text
	GithubTokenExpiresAt pgtype.Timestamp
	PublicRepos          pgtype.Int4
	PublicGists          pgtype.Int4
	Followers            pgtype.Int4
	Following            pgtype.Int4
	Hireable             pgtype.Bool
	Blog                 pgtype.Text
	Company              pgtype.Text
	Location             pgtype.Text
	Bio                  pgtype.Text
	TwitterUsername      pgtype.Text
	TopLanguages         []string
	ContributionCount    pgtype.Int4
}

// CreateOrUpdateUser with extended profile fields (if users table has these columns)
func (q *Queries) CreateOrUpdateUserWithProfile(ctx context.Context, arg CreateOrUpdateUserWithProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, createOrUpdateUserWithProfile,
		arg.GithubID,
		arg.GithubUsername,
		arg.Email,
		arg.AvatarUrl,
		arg.Name,
		arg.GithubAccessToken,
		arg.GithubTokenExpiresAt,
		arg.PublicRepos,
		arg.PublicGists,
		arg.Followers,
		arg.Following,
		arg.Hireable,
		arg.Blog,
		arg.Company,
		arg.Location,
		arg.Bio,
		arg.TwitterUsername,
		arg.TopLanguages,
		arg.ContributionCount,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.Name,
		&i.Role,
		&i.GithubAccessToken,
		&i.GithubTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicRepos,
		&i.PublicGists,
		&i.Followers,
		&i.Following,
		&i.Hireable,
		&i.Blog,
		&i.Company,
		&i.Location,
		&i.Bio,
		&i.TwitterUsername,
		&i.TopLanguages,
		&i.ContributionCount,
	)
	return i, err
}
