// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_snapshots.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGitHubSnapshot = `-- name: CreateGitHubSnapshot :one
INSERT INTO github_snapshots (
    user_id,
    public_repos,
    followers,
    following,
    raw_data
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, public_repos, followers, following, raw_data, fetched_at
`

type CreateGitHubSnapshotParams struct {
	UserID      uuid.UUID
	PublicRepos pgtype.Int4
	Followers   pgtype.Int4
	Following   pgtype.Int4
	RawData     []byte
}

func (q *Queries) CreateGitHubSnapshot(ctx context.Context, arg CreateGitHubSnapshotParams) (GithubSnapshot, error) {
	row := q.db.QueryRow(ctx, createGitHubSnapshot,
		arg.UserID,
		arg.PublicRepos,
		arg.Followers,
		arg.Following,
		arg.RawData,
	)
	var i GithubSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicRepos,
		&i.Followers,
		&i.Following,
		&i.RawData,
		&i.FetchedAt,
	)
	return i, err
}

const getLatestGitHubSnapshot = `-- name: GetLatestGitHubSnapshot :one
SELECT id, user_id, public_repos, followers, following, raw_data, fetched_at FROM github_snapshots
WHERE user_id = $1
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestGitHubSnapshot(ctx context.Context, userID uuid.UUID) (GithubSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestGitHubSnapshot, userID)
	var i GithubSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicRepos,
		&i.Followers,
		&i.Following,
		&i.RawData,
		&i.FetchedAt,
	)
	return i, err
}

const listGitHubSnapshots = `-- name: ListGitHubSnapshots :many
SELECT id, user_id, public_repos, followers, following, raw_data, fetched_at FROM github_snapshots
WHERE user_id = $1
ORDER BY fetched_at DESC
`

func (q *Queries) ListGitHubSnapshots(ctx context.Context, userID uuid.UUID) ([]GithubSnapshot, error) {
	rows, err := q.db.Query(ctx, listGitHubSnapshots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubSnapshot
	for rows.Next() {
		var i GithubSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicRepos,
			&i.Followers,
			&i.Following,
			&i.RawData,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
