// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveJob = `-- name: ArchiveJob :one
UPDATE jobs
SET status = 'archived',
    archived_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND posted_by = $2 AND status IN ('published', 'closed')
RETURNING id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at
`

type ArchiveJobParams struct {
	ID       pgtype.UUID
	PostedBy pgtype.UUID
}

func (q *Queries) ArchiveJob(ctx context.Context, arg ArchiveJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, archiveJob, arg.ID, arg.PostedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeJob = `-- name: CloseJob :one
UPDATE jobs
SET status = 'closed',
    closed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND posted_by = $2 AND status = 'published'
RETURNING id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at
`

type CloseJobParams struct {
	ID       pgtype.UUID
	PostedBy pgtype.UUID
}

func (q *Queries) CloseJob(ctx context.Context, arg CloseJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, closeJob, arg.ID, arg.PostedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    title, company, company_logo, company_website, company_location,
    description, requirements, responsibilities, benefits,
    job_type, experience_level, location, remote_possible,
    salary_min, salary_max, salary_currency,
    status, posted_by, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19
) RETURNING id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at
`

type CreateJobParams struct {
	Title            string
	Company          string
	CompanyLogo      pgtype.Text
	CompanyWebsite   pgtype.Text
	CompanyLocation  pgtype.Text
	Description      string
	Requirements     string
	Responsibilities pgtype.Text
	Benefits         pgtype.Text
	JobType          JobType
	ExperienceLevel  JobExperienceLevel
	Location         pgtype.Text
	RemotePossible   pgtype.Bool
	SalaryMin        pgtype.Int4
	SalaryMax        pgtype.Int4
	SalaryCurrency   pgtype.Text
	Status           JobStatus
	PostedBy         pgtype.UUID
	ExpiresAt        pgtype.Timestamp
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.CompanyLogo,
		arg.CompanyWebsite,
		arg.CompanyLocation,
		arg.Description,
		arg.Requirements,
		arg.Responsibilities,
		arg.Benefits,
		arg.JobType,
		arg.ExperienceLevel,
		arg.Location,
		arg.RemotePossible,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.Status,
		arg.PostedBy,
		arg.ExpiresAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedJobByID = `-- name: GetPublishedJobByID :one
SELECT id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at FROM jobs 
WHERE id = $1 AND status = 'published'
`

func (q *Queries) GetPublishedJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getPublishedJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementJobViews = `-- name: IncrementJobViews :exec
UPDATE jobs SET views_count = views_count + 1 WHERE id = $1
`

func (q *Queries) IncrementJobViews(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementJobViews, id)
	return err
}

const listJobsByPoster = `-- name: ListJobsByPoster :many
SELECT id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at FROM jobs
WHERE posted_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsByPosterParams struct {
	PostedBy pgtype.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListJobsByPoster(ctx context.Context, arg ListJobsByPosterParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByPoster, arg.PostedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.CompanyLogo,
			&i.CompanyWebsite,
			&i.CompanyLocation,
			&i.Description,
			&i.Requirements,
			&i.Responsibilities,
			&i.Benefits,
			&i.JobType,
			&i.ExperienceLevel,
			&i.Location,
			&i.RemotePossible,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.Status,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.ArchivedAt,
			&i.ExpiresAt,
			&i.PostedBy,
			&i.ViewsCount,
			&i.ApplicationsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedJobs = `-- name: ListPublishedJobs :many
SELECT id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at FROM jobs
WHERE status = 'published'
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedJobsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPublishedJobs(ctx context.Context, arg ListPublishedJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listPublishedJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.CompanyLogo,
			&i.CompanyWebsite,
			&i.CompanyLocation,
			&i.Description,
			&i.Requirements,
			&i.Responsibilities,
			&i.Benefits,
			&i.JobType,
			&i.ExperienceLevel,
			&i.Location,
			&i.RemotePossible,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.Status,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.ArchivedAt,
			&i.ExpiresAt,
			&i.PostedBy,
			&i.ViewsCount,
			&i.ApplicationsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishJob = `-- name: PublishJob :one
UPDATE jobs
SET status = 'published',
    published_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND posted_by = $2 AND status = 'draft'
RETURNING id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at
`

type PublishJobParams struct {
	ID       pgtype.UUID
	PostedBy pgtype.UUID
}

// Job lifecycle management
func (q *Queries) PublishJob(ctx context.Context, arg PublishJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, publishJob, arg.ID, arg.PostedBy)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET 
    title = COALESCE($2, title),
    company = COALESCE($3, company),
    description = COALESCE($4, description),
    requirements = COALESCE($5, requirements),
    job_type = COALESCE($6, job_type),
    experience_level = COALESCE($7, experience_level),
    location = COALESCE($8, location),
    remote_possible = COALESCE($9, remote_possible),
    salary_min = COALESCE($10, salary_min),
    salary_max = COALESCE($11, salary_max),
    updated_at = NOW()
WHERE id = $1 AND posted_by = $12
RETURNING id, title, company, company_logo, company_website, company_location, description, requirements, responsibilities, benefits, job_type, experience_level, location, remote_possible, salary_min, salary_max, salary_currency, status, published_at, closed_at, archived_at, expires_at, posted_by, views_count, applications_count, created_at, updated_at
`

type UpdateJobParams struct {
	ID              pgtype.UUID
	Title           string
	Company         string
	Description     string
	Requirements    string
	JobType         JobType
	ExperienceLevel JobExperienceLevel
	Location        pgtype.Text
	RemotePossible  pgtype.Bool
	SalaryMin       pgtype.Int4
	SalaryMax       pgtype.Int4
	PostedBy        pgtype.UUID
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJob,
		arg.ID,
		arg.Title,
		arg.Company,
		arg.Description,
		arg.Requirements,
		arg.JobType,
		arg.ExperienceLevel,
		arg.Location,
		arg.RemotePossible,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.PostedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Company,
		&i.CompanyLogo,
		&i.CompanyWebsite,
		&i.CompanyLocation,
		&i.Description,
		&i.Requirements,
		&i.Responsibilities,
		&i.Benefits,
		&i.JobType,
		&i.ExperienceLevel,
		&i.Location,
		&i.RemotePossible,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.Status,
		&i.PublishedAt,
		&i.ClosedAt,
		&i.ArchivedAt,
		&i.ExpiresAt,
		&i.PostedBy,
		&i.ViewsCount,
		&i.ApplicationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
