// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                   pgtype.UUID
	GithubID             int64
	GithubUsername       string
	Email                pgtype.Text
	AvatarUrl            pgtype.Text
	Name                 pgtype.Text
	Role                 string
	GithubAccessToken    pgtype.Text
	GithubTokenExpiresAt pgtype.Timestamp
	LastLoginAt          pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
}
