// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCodingQuestion = `-- name: CreateCodingQuestion :one

INSERT INTO coding_questions (
    question_id, language, code_template, test_cases,
    execution_time_limit, memory_limit
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, question_id, language, code_template, test_cases, execution_time_limit, memory_limit, created_at
`

type CreateCodingQuestionParams struct {
	QuestionID         pgtype.UUID
	Language           string
	CodeTemplate       pgtype.Text
	TestCases          []byte
	ExecutionTimeLimit pgtype.Int4
	MemoryLimit        pgtype.Int4
}

// Coding questions
func (q *Queries) CreateCodingQuestion(ctx context.Context, arg CreateCodingQuestionParams) (CodingQuestion, error) {
	row := q.db.QueryRow(ctx, createCodingQuestion,
		arg.QuestionID,
		arg.Language,
		arg.CodeTemplate,
		arg.TestCases,
		arg.ExecutionTimeLimit,
		arg.MemoryLimit,
	)
	var i CodingQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Language,
		&i.CodeTemplate,
		&i.TestCases,
		&i.ExecutionTimeLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
	)
	return i, err
}

const createQuestion = `-- name: CreateQuestion :one

INSERT INTO questions (
    question_text, question_type, difficulty, options, correct_answer,
    explanation, time_limit_seconds, points, tags, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at
`

type CreateQuestionParams struct {
	QuestionText     string
	QuestionType     QuestionType
	Difficulty       QuestionDifficulty
	Options          []byte
	CorrectAnswer    pgtype.Text
	Explanation      pgtype.Text
	TimeLimitSeconds pgtype.Int4
	Points           pgtype.Int4
	Tags             []string
	CreatedBy        uuid.UUID
}

// Question CRUD
func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.QuestionText,
		arg.QuestionType,
		arg.Difficulty,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
		arg.TimeLimitSeconds,
		arg.Points,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuestionText,
		&i.QuestionType,
		&i.Difficulty,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.Tags,
		&i.CreatedBy,
		&i.IsActive,
		&i.UsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignTagToQuestion = `-- name: AssignTagToQuestion :exec
INSERT INTO question_tags (question_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignTagToQuestionParams struct {
	QuestionID pgtype.UUID
	TagID      pgtype.UUID
}

func (q *Queries) AssignTagToQuestion(ctx context.Context, arg AssignTagToQuestionParams) error {
	_, err := q.db.Exec(ctx, assignTagToQuestion, arg.QuestionID, arg.TagID)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
UPDATE questions
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const getCodingQuestion = `-- name: GetCodingQuestion :one
SELECT id, question_id, language, code_template, test_cases, execution_time_limit, memory_limit, created_at FROM coding_questions
WHERE question_id = $1
`

func (q *Queries) GetCodingQuestion(ctx context.Context, questionID pgtype.UUID) (CodingQuestion, error) {
	row := q.db.QueryRow(ctx, getCodingQuestion, questionID)
	var i CodingQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Language,
		&i.CodeTemplate,
		&i.TestCases,
		&i.ExecutionTimeLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at FROM questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id pgtype.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuestionText,
		&i.QuestionType,
		&i.Difficulty,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.Tags,
		&i.CreatedBy,
		&i.IsActive,
		&i.UsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionsForQuiz = `-- name: GetQuestionsForQuiz :many
SELECT id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at FROM questions
WHERE id = ANY($1::uuid[])
ORDER BY 
    CASE difficulty
        WHEN 'easy' THEN 1
        WHEN 'medium' THEN 2
        WHEN 'hard' THEN 3
        WHEN 'expert' THEN 4
    END
`

func (q *Queries) GetQuestionsForQuiz(ctx context.Context, dollar_1 []pgtype.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, getQuestionsForQuiz, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.QuestionType,
			&i.Difficulty,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.TimeLimitSeconds,
			&i.Points,
			&i.Tags,
			&i.CreatedBy,
			&i.IsActive,
			&i.UsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomQuestions = `-- name: GetRandomQuestions :many
SELECT id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at FROM questions
WHERE is_active = true
AND difficulty = $1
ORDER BY RANDOM()
LIMIT $2
`

type GetRandomQuestionsParams struct {
	Difficulty QuestionDifficulty
	Limit      int32
}

func (q *Queries) GetRandomQuestions(ctx context.Context, arg GetRandomQuestionsParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, getRandomQuestions, arg.Difficulty, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.QuestionType,
			&i.Difficulty,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.TimeLimitSeconds,
			&i.Points,
			&i.Tags,
			&i.CreatedBy,
			&i.IsActive,
			&i.UsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementQuestionUsage = `-- name: IncrementQuestionUsage :exec
UPDATE questions
SET usage_count = usage_count + 1
WHERE id = $1
`

func (q *Queries) IncrementQuestionUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementQuestionUsage, id)
	return err
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at FROM questions
WHERE is_active = true
ORDER BY difficulty, created_at DESC
LIMIT $1 OFFSET $2
`

type ListQuestionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.QuestionType,
			&i.Difficulty,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.TimeLimitSeconds,
			&i.Points,
			&i.Tags,
			&i.CreatedBy,
			&i.IsActive,
			&i.UsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByDifficulty = `-- name: ListQuestionsByDifficulty :many
SELECT id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at FROM questions
WHERE difficulty = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListQuestionsByDifficultyParams struct {
	Difficulty QuestionDifficulty
	Limit      int32
	Offset     int32
}

func (q *Queries) ListQuestionsByDifficulty(ctx context.Context, arg ListQuestionsByDifficultyParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByDifficulty, arg.Difficulty, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.QuestionType,
			&i.Difficulty,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.TimeLimitSeconds,
			&i.Points,
			&i.Tags,
			&i.CreatedBy,
			&i.IsActive,
			&i.UsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByTag = `-- name: ListQuestionsByTag :many
SELECT q.id, q.question_text, q.question_type, q.difficulty, q.options, q.correct_answer, q.explanation, q.time_limit_seconds, q.points, q.tags, q.created_by, q.is_active, q.usage_count, q.created_at, q.updated_at FROM questions q
WHERE $1 = ANY(q.tags) AND is_active = true
ORDER BY q.difficulty, q.created_at DESC
LIMIT $2 OFFSET $3
`

type ListQuestionsByTagParams struct {
	Tags   []string
	Limit  int32
	Offset int32
}

func (q *Queries) ListQuestionsByTag(ctx context.Context, arg ListQuestionsByTagParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByTag, arg.Tags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.QuestionText,
			&i.QuestionType,
			&i.Difficulty,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.TimeLimitSeconds,
			&i.Points,
			&i.Tags,
			&i.CreatedBy,
			&i.IsActive,
			&i.UsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCodingQuestion = `-- name: UpdateCodingQuestion :one
UPDATE coding_questions
SET 
    language = COALESCE($2, language),
    code_template = COALESCE($3, code_template),
    test_cases = COALESCE($4, test_cases),
    execution_time_limit = COALESCE($5, execution_time_limit),
    memory_limit = COALESCE($6, memory_limit)
WHERE question_id = $1
RETURNING id, question_id, language, code_template, test_cases, execution_time_limit, memory_limit, created_at
`

type UpdateCodingQuestionParams struct {
	QuestionID         pgtype.UUID
	Language           string
	CodeTemplate       pgtype.Text
	TestCases          []byte
	ExecutionTimeLimit pgtype.Int4
	MemoryLimit        pgtype.Int4
}

func (q *Queries) UpdateCodingQuestion(ctx context.Context, arg UpdateCodingQuestionParams) (CodingQuestion, error) {
	row := q.db.QueryRow(ctx, updateCodingQuestion,
		arg.QuestionID,
		arg.Language,
		arg.CodeTemplate,
		arg.TestCases,
		arg.ExecutionTimeLimit,
		arg.MemoryLimit,
	)
	var i CodingQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Language,
		&i.CodeTemplate,
		&i.TestCases,
		&i.ExecutionTimeLimit,
		&i.MemoryLimit,
		&i.CreatedAt,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET 
    question_text = COALESCE($2, question_text),
    options = COALESCE($3, options),
    correct_answer = COALESCE($4, correct_answer),
    explanation = COALESCE($5, explanation),
    time_limit_seconds = COALESCE($6, time_limit_seconds),
    points = COALESCE($7, points),
    tags = COALESCE($8, tags),
    updated_at = NOW()
WHERE id = $1
RETURNING id, question_text, question_type, difficulty, options, correct_answer, explanation, time_limit_seconds, points, tags, created_by, is_active, usage_count, created_at, updated_at
`

type UpdateQuestionParams struct {
	ID               pgtype.UUID
	QuestionText     string
	Options          []byte
	CorrectAnswer    pgtype.Text
	Explanation      pgtype.Text
	TimeLimitSeconds pgtype.Int4
	Points           pgtype.Int4
	Tags             []string
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.QuestionText,
		arg.Options,
		arg.CorrectAnswer,
		arg.Explanation,
		arg.TimeLimitSeconds,
		arg.Points,
		arg.Tags,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.QuestionText,
		&i.QuestionType,
		&i.Difficulty,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.TimeLimitSeconds,
		&i.Points,
		&i.Tags,
		&i.CreatedBy,
		&i.IsActive,
		&i.UsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
