// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question_feedback.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuestionFeedback = `-- name: GetQuestionFeedback :one
SELECT feedback
FROM question_feedback
WHERE user_id = $1 AND question_id = $2
`

type GetQuestionFeedbackParams struct {
	UserID     pgtype.UUID
	QuestionID pgtype.UUID
}

func (q *Queries) GetQuestionFeedback(ctx context.Context, arg GetQuestionFeedbackParams) (string, error) {
	row := q.db.QueryRow(ctx, getQuestionFeedback, arg.UserID, arg.QuestionID)
	var feedback string
	err := row.Scan(&feedback)
	return feedback, err
}

const upsertQuestionFeedback = `-- name: UpsertQuestionFeedback :one
INSERT INTO question_feedback (user_id, question_id, feedback)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, question_id)
DO UPDATE SET feedback = EXCLUDED.feedback, updated_at = NOW()
RETURNING feedback
`

type UpsertQuestionFeedbackParams struct {
	UserID     pgtype.UUID
	QuestionID pgtype.UUID
	Feedback   string
}

func (q *Queries) UpsertQuestionFeedback(ctx context.Context, arg UpsertQuestionFeedbackParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertQuestionFeedback, arg.UserID, arg.QuestionID, arg.Feedback)
	var feedback string
	err := row.Scan(&feedback)
	return feedback, err
}
