// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_attempts.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoSaveQuiz = `-- name: AutoSaveQuiz :exec
UPDATE quiz_attempts
SET 
    last_activity_at = NOW(),
    time_spent_seconds = time_spent_seconds + $2
WHERE id = $1
`

type AutoSaveQuizParams struct {
	ID               pgtype.UUID
	TimeSpentSeconds pgtype.Int4
}

func (q *Queries) AutoSaveQuiz(ctx context.Context, arg AutoSaveQuizParams) error {
	_, err := q.db.Exec(ctx, autoSaveQuiz, arg.ID, arg.TimeSpentSeconds)
	return err
}

const completeQuiz = `-- name: CompleteQuiz :one
UPDATE quiz_attempts
SET 
    status = 'completed',
    completed_at = NOW(),
    score = $2,
    correct_answers = $3,
    incorrect_answers = $4,
    skipped_questions = $5,
    passed = $6,
    updated_at = NOW()
WHERE id = $1 AND status IN ('in_progress', 'paused')
RETURNING id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at
`

type CompleteQuizParams struct {
	ID               pgtype.UUID
	Score            pgtype.Int4
	CorrectAnswers   pgtype.Int4
	IncorrectAnswers pgtype.Int4
	SkippedQuestions pgtype.Int4
	Passed           pgtype.Bool
}

func (q *Queries) CompleteQuiz(ctx context.Context, arg CompleteQuizParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, completeQuiz,
		arg.ID,
		arg.Score,
		arg.CorrectAnswers,
		arg.IncorrectAnswers,
		arg.SkippedQuestions,
		arg.Passed,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuizAttempt = `-- name: CreateQuizAttempt :one

INSERT INTO quiz_attempts (
    application_id, user_id, job_id, total_questions,
    questions_per_quiz, time_limit_minutes, passing_score
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at
`

type CreateQuizAttemptParams struct {
	ApplicationID    pgtype.UUID
	UserID           pgtype.UUID
	JobID            pgtype.UUID
	TotalQuestions   int32
	QuestionsPerQuiz int32
	TimeLimitMinutes pgtype.Int4
	PassingScore     int32
}

// Quiz attempt management
func (q *Queries) CreateQuizAttempt(ctx context.Context, arg CreateQuizAttemptParams) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, createQuizAttempt,
		arg.ApplicationID,
		arg.UserID,
		arg.JobID,
		arg.TotalQuestions,
		arg.QuestionsPerQuiz,
		arg.TimeLimitMinutes,
		arg.PassingScore,
	)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuizResults = `-- name: CreateQuizResults :one

INSERT INTO quiz_results (
    quiz_attempt_id, easy_correct, easy_total,
    medium_correct, medium_total,
    hard_correct, hard_total,
    expert_correct, expert_total,
    multiple_choice_correct, multiple_choice_total,
    coding_correct, coding_total,
    avg_time_per_question_seconds,
    fastest_question_time_seconds,
    slowest_question_time_seconds,
    ai_feedback, strengths, weaknesses
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, quiz_attempt_id, easy_correct, easy_total, medium_correct, medium_total, hard_correct, hard_total, expert_correct, expert_total, multiple_choice_correct, multiple_choice_total, coding_correct, coding_total, avg_time_per_question_seconds, fastest_question_time_seconds, slowest_question_time_seconds, ai_feedback, strengths, weaknesses, created_at
`

type CreateQuizResultsParams struct {
	QuizAttemptID              pgtype.UUID
	EasyCorrect                pgtype.Int4
	EasyTotal                  pgtype.Int4
	MediumCorrect              pgtype.Int4
	MediumTotal                pgtype.Int4
	HardCorrect                pgtype.Int4
	HardTotal                  pgtype.Int4
	ExpertCorrect              pgtype.Int4
	ExpertTotal                pgtype.Int4
	MultipleChoiceCorrect      pgtype.Int4
	MultipleChoiceTotal        pgtype.Int4
	CodingCorrect              pgtype.Int4
	CodingTotal                pgtype.Int4
	AvgTimePerQuestionSeconds  pgtype.Float8
	FastestQuestionTimeSeconds pgtype.Int4
	SlowestQuestionTimeSeconds pgtype.Int4
	AiFeedback                 pgtype.Text
	Strengths                  []string
	Weaknesses                 []string
}

// Quiz results
func (q *Queries) CreateQuizResults(ctx context.Context, arg CreateQuizResultsParams) (QuizResult, error) {
	row := q.db.QueryRow(ctx, createQuizResults,
		arg.QuizAttemptID,
		arg.EasyCorrect,
		arg.EasyTotal,
		arg.MediumCorrect,
		arg.MediumTotal,
		arg.HardCorrect,
		arg.HardTotal,
		arg.ExpertCorrect,
		arg.ExpertTotal,
		arg.MultipleChoiceCorrect,
		arg.MultipleChoiceTotal,
		arg.CodingCorrect,
		arg.CodingTotal,
		arg.AvgTimePerQuestionSeconds,
		arg.FastestQuestionTimeSeconds,
		arg.SlowestQuestionTimeSeconds,
		arg.AiFeedback,
		arg.Strengths,
		arg.Weaknesses,
	)
	var i QuizResult
	err := row.Scan(
		&i.ID,
		&i.QuizAttemptID,
		&i.EasyCorrect,
		&i.EasyTotal,
		&i.MediumCorrect,
		&i.MediumTotal,
		&i.HardCorrect,
		&i.HardTotal,
		&i.ExpertCorrect,
		&i.ExpertTotal,
		&i.MultipleChoiceCorrect,
		&i.MultipleChoiceTotal,
		&i.CodingCorrect,
		&i.CodingTotal,
		&i.AvgTimePerQuestionSeconds,
		&i.FastestQuestionTimeSeconds,
		&i.SlowestQuestionTimeSeconds,
		&i.AiFeedback,
		&i.Strengths,
		&i.Weaknesses,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveQuizAttempt = `-- name: GetActiveQuizAttempt :one
SELECT id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at FROM quiz_attempts
WHERE user_id = $1 
AND status IN ('started', 'in_progress', 'paused')
ORDER BY last_activity_at DESC
LIMIT 1
`

func (q *Queries) GetActiveQuizAttempt(ctx context.Context, userID pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getActiveQuizAttempt, userID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnswer = `-- name: GetAnswer :one
SELECT id, quiz_attempt_id, question_id, user_answer, is_correct, last_saved_at, save_count, time_spent_seconds, code_output, execution_time_ms, memory_used_mb, is_skipped, is_reviewed, created_at, updated_at FROM quiz_answers
WHERE quiz_attempt_id = $1 AND question_id = $2
`

type GetAnswerParams struct {
	QuizAttemptID pgtype.UUID
	QuestionID    pgtype.UUID
}

func (q *Queries) GetAnswer(ctx context.Context, arg GetAnswerParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, getAnswer, arg.QuizAttemptID, arg.QuestionID)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.QuizAttemptID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
		&i.LastSavedAt,
		&i.SaveCount,
		&i.TimeSpentSeconds,
		&i.CodeOutput,
		&i.ExecutionTimeMs,
		&i.MemoryUsedMb,
		&i.IsSkipped,
		&i.IsReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnswerHistory = `-- name: GetAnswerHistory :many
SELECT id, quiz_answer_id, user_answer, time_spent_seconds, saved_at, save_reason, ip_address, user_agent FROM quiz_answer_history
WHERE quiz_answer_id = $1
ORDER BY saved_at DESC
`

func (q *Queries) GetAnswerHistory(ctx context.Context, quizAnswerID pgtype.UUID) ([]QuizAnswerHistory, error) {
	rows, err := q.db.Query(ctx, getAnswerHistory, quizAnswerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAnswerHistory
	for rows.Next() {
		var i QuizAnswerHistory
		if err := rows.Scan(
			&i.ID,
			&i.QuizAnswerID,
			&i.UserAnswer,
			&i.TimeSpentSeconds,
			&i.SavedAt,
			&i.SaveReason,
			&i.IpAddress,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnsweredQuestions = `-- name: GetAnsweredQuestions :many
SELECT question_id, is_correct, time_spent_seconds
FROM quiz_answers
WHERE quiz_attempt_id = $1
`

type GetAnsweredQuestionsRow struct {
	QuestionID       pgtype.UUID
	IsCorrect        pgtype.Bool
	TimeSpentSeconds pgtype.Int4
}

func (q *Queries) GetAnsweredQuestions(ctx context.Context, quizAttemptID pgtype.UUID) ([]GetAnsweredQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getAnsweredQuestions, quizAttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnsweredQuestionsRow
	for rows.Next() {
		var i GetAnsweredQuestionsRow
		if err := rows.Scan(&i.QuestionID, &i.IsCorrect, &i.TimeSpentSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizAnalytics = `-- name: GetQuizAnalytics :many
SELECT 
    DATE(completed_at) as date,
    COUNT(*) as total_attempts,
    AVG(score) as avg_score,
    COUNT(CASE WHEN passed THEN 1 END) as passed_count
FROM quiz_attempts
WHERE completed_at BETWEEN $1 AND $2
GROUP BY DATE(completed_at)
ORDER BY date
`

type GetQuizAnalyticsParams struct {
	CompletedAt   pgtype.Timestamp
	CompletedAt_2 pgtype.Timestamp
}

type GetQuizAnalyticsRow struct {
	Date          pgtype.Date
	TotalAttempts int64
	AvgScore      float64
	PassedCount   int64
}

func (q *Queries) GetQuizAnalytics(ctx context.Context, arg GetQuizAnalyticsParams) ([]GetQuizAnalyticsRow, error) {
	rows, err := q.db.Query(ctx, getQuizAnalytics, arg.CompletedAt, arg.CompletedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizAnalyticsRow
	for rows.Next() {
		var i GetQuizAnalyticsRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalAttempts,
			&i.AvgScore,
			&i.PassedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuizAttemptByApplication = `-- name: GetQuizAttemptByApplication :one
SELECT id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at FROM quiz_attempts
WHERE application_id = $1
`

func (q *Queries) GetQuizAttemptByApplication(ctx context.Context, applicationID pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getQuizAttemptByApplication, applicationID)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizAttemptByID = `-- name: GetQuizAttemptByID :one
SELECT id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at FROM quiz_attempts WHERE id = $1
`

func (q *Queries) GetQuizAttemptByID(ctx context.Context, id pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, getQuizAttemptByID, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizResults = `-- name: GetQuizResults :one
SELECT id, quiz_attempt_id, easy_correct, easy_total, medium_correct, medium_total, hard_correct, hard_total, expert_correct, expert_total, multiple_choice_correct, multiple_choice_total, coding_correct, coding_total, avg_time_per_question_seconds, fastest_question_time_seconds, slowest_question_time_seconds, ai_feedback, strengths, weaknesses, created_at FROM quiz_results
WHERE quiz_attempt_id = $1
`

func (q *Queries) GetQuizResults(ctx context.Context, quizAttemptID pgtype.UUID) (QuizResult, error) {
	row := q.db.QueryRow(ctx, getQuizResults, quizAttemptID)
	var i QuizResult
	err := row.Scan(
		&i.ID,
		&i.QuizAttemptID,
		&i.EasyCorrect,
		&i.EasyTotal,
		&i.MediumCorrect,
		&i.MediumTotal,
		&i.HardCorrect,
		&i.HardTotal,
		&i.ExpertCorrect,
		&i.ExpertTotal,
		&i.MultipleChoiceCorrect,
		&i.MultipleChoiceTotal,
		&i.CodingCorrect,
		&i.CodingTotal,
		&i.AvgTimePerQuestionSeconds,
		&i.FastestQuestionTimeSeconds,
		&i.SlowestQuestionTimeSeconds,
		&i.AiFeedback,
		&i.Strengths,
		&i.Weaknesses,
		&i.CreatedAt,
	)
	return i, err
}

const getUserQuizStats = `-- name: GetUserQuizStats :many

SELECT 
    qa.id, qa.application_id, qa.user_id, qa.job_id, qa.total_questions, qa.questions_per_quiz, qa.time_limit_minutes, qa.passing_score, qa.status, qa.started_at, qa.completed_at, qa.last_activity_at, qa.score, qa.correct_answers, qa.incorrect_answers, qa.skipped_questions, qa.passed, qa.time_spent_seconds, qa.auto_save_interval_seconds, qa.created_at, qa.updated_at,
    j.title as job_title,
    j.company as job_company,
    qa.score,
    qa.passed,
    qr.strengths,
    qr.weaknesses
FROM quiz_attempts qa
JOIN jobs j ON qa.job_id = j.id
LEFT JOIN quiz_results qr ON qa.id = qr.quiz_attempt_id
WHERE qa.user_id = $1 AND qa.status = 'completed'
ORDER BY qa.completed_at DESC
LIMIT $2 OFFSET $3
`

type GetUserQuizStatsParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type GetUserQuizStatsRow struct {
	ID                      pgtype.UUID
	ApplicationID           pgtype.UUID
	UserID                  pgtype.UUID
	JobID                   pgtype.UUID
	TotalQuestions          int32
	QuestionsPerQuiz        int32
	TimeLimitMinutes        pgtype.Int4
	PassingScore            int32
	Status                  QuizAttemptStatus
	StartedAt               pgtype.Timestamp
	CompletedAt             pgtype.Timestamp
	LastActivityAt          pgtype.Timestamp
	Score                   pgtype.Int4
	CorrectAnswers          pgtype.Int4
	IncorrectAnswers        pgtype.Int4
	SkippedQuestions        pgtype.Int4
	Passed                  pgtype.Bool
	TimeSpentSeconds        pgtype.Int4
	AutoSaveIntervalSeconds pgtype.Int4
	CreatedAt               pgtype.Timestamp
	UpdatedAt               pgtype.Timestamp
	JobTitle                string
	JobCompany              string
	Score_2                 pgtype.Int4
	Passed_2                pgtype.Bool
	Strengths               []string
	Weaknesses              []string
}

// Statistics
func (q *Queries) GetUserQuizStats(ctx context.Context, arg GetUserQuizStatsParams) ([]GetUserQuizStatsRow, error) {
	rows, err := q.db.Query(ctx, getUserQuizStats, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserQuizStatsRow
	for rows.Next() {
		var i GetUserQuizStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.UserID,
			&i.JobID,
			&i.TotalQuestions,
			&i.QuestionsPerQuiz,
			&i.TimeLimitMinutes,
			&i.PassingScore,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.LastActivityAt,
			&i.Score,
			&i.CorrectAnswers,
			&i.IncorrectAnswers,
			&i.SkippedQuestions,
			&i.Passed,
			&i.TimeSpentSeconds,
			&i.AutoSaveIntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JobTitle,
			&i.JobCompany,
			&i.Score_2,
			&i.Passed_2,
			&i.Strengths,
			&i.Weaknesses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserQuizAnswers = `-- name: GetUserQuizAnswers :many
SELECT 
    qa.id, qa.quiz_attempt_id, qa.question_id, qa.user_answer, qa.is_correct, qa.last_saved_at, qa.save_count, qa.time_spent_seconds, qa.code_output, qa.execution_time_ms, qa.memory_used_mb, qa.is_skipped, qa.is_reviewed, qa.created_at, qa.updated_at
FROM quiz_answers qa
JOIN quiz_attempts qat ON qa.quiz_attempt_id = qat.id
WHERE qat.user_id = $1
ORDER BY qa.created_at DESC
`

func (q *Queries) GetUserQuizAnswers(ctx context.Context, userID pgtype.UUID) ([]QuizAnswer, error) {
	rows, err := q.db.Query(ctx, getUserQuizAnswers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAnswer
	for rows.Next() {
		var i QuizAnswer
		if err := rows.Scan(
			&i.ID,
			&i.QuizAttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
			&i.LastSavedAt,
			&i.SaveCount,
			&i.TimeSpentSeconds,
			&i.CodeOutput,
			&i.ExecutionTimeMs,
			&i.MemoryUsedMb,
			&i.IsSkipped,
			&i.IsReviewed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswers = `-- name: ListAnswers :many
SELECT id, quiz_attempt_id, question_id, user_answer, is_correct, last_saved_at, save_count, time_spent_seconds, code_output, execution_time_ms, memory_used_mb, is_skipped, is_reviewed, created_at, updated_at FROM quiz_answers
WHERE quiz_attempt_id = $1
ORDER BY created_at
`

func (q *Queries) ListAnswers(ctx context.Context, quizAttemptID pgtype.UUID) ([]QuizAnswer, error) {
	rows, err := q.db.Query(ctx, listAnswers, quizAttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAnswer
	for rows.Next() {
		var i QuizAnswer
		if err := rows.Scan(
			&i.ID,
			&i.QuizAttemptID,
			&i.QuestionID,
			&i.UserAnswer,
			&i.IsCorrect,
			&i.LastSavedAt,
			&i.SaveCount,
			&i.TimeSpentSeconds,
			&i.CodeOutput,
			&i.ExecutionTimeMs,
			&i.MemoryUsedMb,
			&i.IsSkipped,
			&i.IsReviewed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markForReview = `-- name: MarkForReview :exec
UPDATE quiz_answers
SET is_reviewed = true
WHERE quiz_attempt_id = $1 AND question_id = $2
`

type MarkForReviewParams struct {
	QuizAttemptID pgtype.UUID
	QuestionID    pgtype.UUID
}

func (q *Queries) MarkForReview(ctx context.Context, arg MarkForReviewParams) error {
	_, err := q.db.Exec(ctx, markForReview, arg.QuizAttemptID, arg.QuestionID)
	return err
}

const pauseQuiz = `-- name: PauseQuiz :one
UPDATE quiz_attempts
SET 
    status = 'paused',
    last_activity_at = NOW()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at
`

func (q *Queries) PauseQuiz(ctx context.Context, id pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, pauseQuiz, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeQuiz = `-- name: ResumeQuiz :one
UPDATE quiz_attempts
SET 
    status = 'in_progress',
    last_activity_at = NOW()
WHERE id = $1 AND status = 'paused'
RETURNING id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at
`

func (q *Queries) ResumeQuiz(ctx context.Context, id pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, resumeQuiz, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveAnswer = `-- name: SaveAnswer :one

INSERT INTO quiz_answers (
    quiz_attempt_id, question_id, user_answer, is_correct,
    time_spent_seconds, is_skipped
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (quiz_attempt_id, question_id) 
DO UPDATE SET
    user_answer = EXCLUDED.user_answer,
    is_correct = EXCLUDED.is_correct,
    time_spent_seconds = quiz_answers.time_spent_seconds + EXCLUDED.time_spent_seconds,
    is_skipped = EXCLUDED.is_skipped,
    save_count = quiz_answers.save_count + 1,
    last_saved_at = NOW(),
    updated_at = NOW()
RETURNING id, quiz_attempt_id, question_id, user_answer, is_correct, last_saved_at, save_count, time_spent_seconds, code_output, execution_time_ms, memory_used_mb, is_skipped, is_reviewed, created_at, updated_at
`

type SaveAnswerParams struct {
	QuizAttemptID    pgtype.UUID
	QuestionID       pgtype.UUID
	UserAnswer       pgtype.Text
	IsCorrect        pgtype.Bool
	TimeSpentSeconds pgtype.Int4
	IsSkipped        pgtype.Bool
}

// Quiz answers
func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) (QuizAnswer, error) {
	row := q.db.QueryRow(ctx, saveAnswer,
		arg.QuizAttemptID,
		arg.QuestionID,
		arg.UserAnswer,
		arg.IsCorrect,
		arg.TimeSpentSeconds,
		arg.IsSkipped,
	)
	var i QuizAnswer
	err := row.Scan(
		&i.ID,
		&i.QuizAttemptID,
		&i.QuestionID,
		&i.UserAnswer,
		&i.IsCorrect,
		&i.LastSavedAt,
		&i.SaveCount,
		&i.TimeSpentSeconds,
		&i.CodeOutput,
		&i.ExecutionTimeMs,
		&i.MemoryUsedMb,
		&i.IsSkipped,
		&i.IsReviewed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveAnswerHistory = `-- name: SaveAnswerHistory :exec

INSERT INTO quiz_answer_history (
    quiz_answer_id, user_answer, time_spent_seconds,
    save_reason, ip_address, user_agent
) VALUES ($1, $2, $3, $4, $5, $6)
`

type SaveAnswerHistoryParams struct {
	QuizAnswerID     pgtype.UUID
	UserAnswer       pgtype.Text
	TimeSpentSeconds pgtype.Int4
	SaveReason       pgtype.Text
	IpAddress        *netip.Addr
	UserAgent        pgtype.Text
}

// Answer history
func (q *Queries) SaveAnswerHistory(ctx context.Context, arg SaveAnswerHistoryParams) error {
	_, err := q.db.Exec(ctx, saveAnswerHistory,
		arg.QuizAnswerID,
		arg.UserAnswer,
		arg.TimeSpentSeconds,
		arg.SaveReason,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const startQuiz = `-- name: StartQuiz :one

UPDATE quiz_attempts
SET 
    status = 'in_progress',
    last_activity_at = NOW()
WHERE id = $1 AND status = 'started'
RETURNING id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at
`

// Status updates
func (q *Queries) StartQuiz(ctx context.Context, id pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, startQuiz, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const timeoutQuiz = `-- name: TimeoutQuiz :one
UPDATE quiz_attempts
SET 
    status = 'timed_out',
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, application_id, user_id, job_id, total_questions, questions_per_quiz, time_limit_minutes, passing_score, status, started_at, completed_at, last_activity_at, score, correct_answers, incorrect_answers, skipped_questions, passed, time_spent_seconds, auto_save_interval_seconds, created_at, updated_at
`

func (q *Queries) TimeoutQuiz(ctx context.Context, id pgtype.UUID) (QuizAttempt, error) {
	row := q.db.QueryRow(ctx, timeoutQuiz, id)
	var i QuizAttempt
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.UserID,
		&i.JobID,
		&i.TotalQuestions,
		&i.QuestionsPerQuiz,
		&i.TimeLimitMinutes,
		&i.PassingScore,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.LastActivityAt,
		&i.Score,
		&i.CorrectAnswers,
		&i.IncorrectAnswers,
		&i.SkippedQuestions,
		&i.Passed,
		&i.TimeSpentSeconds,
		&i.AutoSaveIntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAIFeedback = `-- name: UpdateAIFeedback :exec
UPDATE quiz_results
SET 
    ai_feedback = $2,
    strengths = $3,
    weaknesses = $4
WHERE quiz_attempt_id = $1
`

type UpdateAIFeedbackParams struct {
	QuizAttemptID pgtype.UUID
	AiFeedback    pgtype.Text
	Strengths     []string
	Weaknesses    []string
}

func (q *Queries) UpdateAIFeedback(ctx context.Context, arg UpdateAIFeedbackParams) error {
	_, err := q.db.Exec(ctx, updateAIFeedback,
		arg.QuizAttemptID,
		arg.AiFeedback,
		arg.Strengths,
		arg.Weaknesses,
	)
	return err
}
