// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz_answer_feedback.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteQuizAnswerFeedback = `-- name: DeleteQuizAnswerFeedback :exec
DELETE FROM quiz_answer_feedback
WHERE user_id = $1 AND quiz_attempt_id = $2 AND question_id = $3
`

type DeleteQuizAnswerFeedbackParams struct {
	UserID        pgtype.UUID
	QuizAttemptID pgtype.UUID
	QuestionID    pgtype.UUID
}

func (q *Queries) DeleteQuizAnswerFeedback(ctx context.Context, arg DeleteQuizAnswerFeedbackParams) error {
	_, err := q.db.Exec(ctx, deleteQuizAnswerFeedback, arg.UserID, arg.QuizAttemptID, arg.QuestionID)
	return err
}

const deleteQuizAnswerFeedbackByAttempt = `-- name: DeleteQuizAnswerFeedbackByAttempt :exec
DELETE FROM quiz_answer_feedback
WHERE user_id = $1 AND quiz_attempt_id = $2
`

type DeleteQuizAnswerFeedbackByAttemptParams struct {
	UserID        pgtype.UUID
	QuizAttemptID pgtype.UUID
}

func (q *Queries) DeleteQuizAnswerFeedbackByAttempt(ctx context.Context, arg DeleteQuizAnswerFeedbackByAttemptParams) error {
	_, err := q.db.Exec(ctx, deleteQuizAnswerFeedbackByAttempt, arg.UserID, arg.QuizAttemptID)
	return err
}

const getQuizAnswerFeedback = `-- name: GetQuizAnswerFeedback :one
SELECT id, user_id, quiz_attempt_id, question_id, application_id, feedback, created_at, updated_at FROM quiz_answer_feedback
WHERE user_id = $1 AND quiz_attempt_id = $2 AND question_id = $3
`

type GetQuizAnswerFeedbackParams struct {
	UserID        pgtype.UUID
	QuizAttemptID pgtype.UUID
	QuestionID    pgtype.UUID
}

func (q *Queries) GetQuizAnswerFeedback(ctx context.Context, arg GetQuizAnswerFeedbackParams) (QuizAnswerFeedback, error) {
	row := q.db.QueryRow(ctx, getQuizAnswerFeedback, arg.UserID, arg.QuizAttemptID, arg.QuestionID)
	var i QuizAnswerFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizAttemptID,
		&i.QuestionID,
		&i.ApplicationID,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuizAnswerFeedbackByAttempt = `-- name: GetQuizAnswerFeedbackByAttempt :many
SELECT id, user_id, quiz_attempt_id, question_id, application_id, feedback, created_at, updated_at FROM quiz_answer_feedback
WHERE user_id = $1 AND quiz_attempt_id = $2
ORDER BY created_at ASC
`

type GetQuizAnswerFeedbackByAttemptParams struct {
	UserID        pgtype.UUID
	QuizAttemptID pgtype.UUID
}

func (q *Queries) GetQuizAnswerFeedbackByAttempt(ctx context.Context, arg GetQuizAnswerFeedbackByAttemptParams) ([]QuizAnswerFeedback, error) {
	rows, err := q.db.Query(ctx, getQuizAnswerFeedbackByAttempt, arg.UserID, arg.QuizAttemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAnswerFeedback
	for rows.Next() {
		var i QuizAnswerFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizAttemptID,
			&i.QuestionID,
			&i.ApplicationID,
			&i.Feedback,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuizAnswerFeedbackByApplication = `-- name: ListQuizAnswerFeedbackByApplication :many
SELECT id, user_id, quiz_attempt_id, question_id, application_id, feedback, created_at, updated_at FROM quiz_answer_feedback
WHERE application_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListQuizAnswerFeedbackByApplication(ctx context.Context, applicationID pgtype.UUID) ([]QuizAnswerFeedback, error) {
	rows, err := q.db.Query(ctx, listQuizAnswerFeedbackByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAnswerFeedback
	for rows.Next() {
		var i QuizAnswerFeedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.QuizAttemptID,
			&i.QuestionID,
			&i.ApplicationID,
			&i.Feedback,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertQuizAnswerFeedback = `-- name: UpsertQuizAnswerFeedback :one
INSERT INTO quiz_answer_feedback (user_id, quiz_attempt_id, question_id, application_id, feedback)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, quiz_attempt_id, question_id)
DO UPDATE SET
    feedback = EXCLUDED.feedback,
    updated_at = NOW()
RETURNING id, user_id, quiz_attempt_id, question_id, application_id, feedback, created_at, updated_at
`

type UpsertQuizAnswerFeedbackParams struct {
	UserID        pgtype.UUID
	QuizAttemptID pgtype.UUID
	QuestionID    pgtype.UUID
	ApplicationID pgtype.UUID
	Feedback      string
}

func (q *Queries) UpsertQuizAnswerFeedback(ctx context.Context, arg UpsertQuizAnswerFeedbackParams) (QuizAnswerFeedback, error) {
	row := q.db.QueryRow(ctx, upsertQuizAnswerFeedback,
		arg.UserID,
		arg.QuizAttemptID,
		arg.QuestionID,
		arg.ApplicationID,
		arg.Feedback,
	)
	var i QuizAnswerFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuizAttemptID,
		&i.QuestionID,
		&i.ApplicationID,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
