// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repository_analysis.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRepositoryAnalysis = `-- name: CreateRepositoryAnalysis :one
INSERT INTO repository_analysis (
    user_id,
    repo_name,
    language,
    score,
    has_readme,
    stars,
    forks,
    signals
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, repo_name, language, score, has_readme, stars, forks, signals, analyzed_at
`

type CreateRepositoryAnalysisParams struct {
	UserID    uuid.UUID
	RepoName  string
	Language  pgtype.Text
	Score     pgtype.Int4
	HasReadme pgtype.Bool
	Stars     pgtype.Int4
	Forks     pgtype.Int4
	Signals   []byte
}

func (q *Queries) CreateRepositoryAnalysis(ctx context.Context, arg CreateRepositoryAnalysisParams) (RepositoryAnalysis, error) {
	row := q.db.QueryRow(ctx, createRepositoryAnalysis,
		arg.UserID,
		arg.RepoName,
		arg.Language,
		arg.Score,
		arg.HasReadme,
		arg.Stars,
		arg.Forks,
		arg.Signals,
	)
	var i RepositoryAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoName,
		&i.Language,
		&i.Score,
		&i.HasReadme,
		&i.Stars,
		&i.Forks,
		&i.Signals,
		&i.AnalyzedAt,
	)
	return i, err
}

const deleteRepositoryAnalysisByUser = `-- name: DeleteRepositoryAnalysisByUser :exec
DELETE FROM repository_analysis
WHERE user_id = $1
`

func (q *Queries) DeleteRepositoryAnalysisByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepositoryAnalysisByUser, userID)
	return err
}

const getLatestRepositoryAnalysisByRepo = `-- name: GetLatestRepositoryAnalysisByRepo :one
SELECT id, user_id, repo_name, language, score, has_readme, stars, forks, signals, analyzed_at FROM repository_analysis
WHERE user_id = $1 AND repo_name = $2
ORDER BY analyzed_at DESC
LIMIT 1
`

type GetLatestRepositoryAnalysisByRepoParams struct {
	UserID   uuid.UUID
	RepoName string
}

func (q *Queries) GetLatestRepositoryAnalysisByRepo(ctx context.Context, arg GetLatestRepositoryAnalysisByRepoParams) (RepositoryAnalysis, error) {
	row := q.db.QueryRow(ctx, getLatestRepositoryAnalysisByRepo, arg.UserID, arg.RepoName)
	var i RepositoryAnalysis
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RepoName,
		&i.Language,
		&i.Score,
		&i.HasReadme,
		&i.Stars,
		&i.Forks,
		&i.Signals,
		&i.AnalyzedAt,
	)
	return i, err
}

const getRepositoryAnalysisByUser = `-- name: GetRepositoryAnalysisByUser :many
SELECT id, user_id, repo_name, language, score, has_readme, stars, forks, signals, analyzed_at FROM repository_analysis
WHERE user_id = $1
ORDER BY analyzed_at DESC
`

func (q *Queries) GetRepositoryAnalysisByUser(ctx context.Context, userID uuid.UUID) ([]RepositoryAnalysis, error) {
	rows, err := q.db.Query(ctx, getRepositoryAnalysisByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositoryAnalysis
	for rows.Next() {
		var i RepositoryAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RepoName,
			&i.Language,
			&i.Score,
			&i.HasReadme,
			&i.Stars,
			&i.Forks,
			&i.Signals,
			&i.AnalyzedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
