// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_jobs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSavedJobsByUser = `-- name: CountSavedJobsByUser :one
SELECT COUNT(*) FROM saved_jobs
WHERE user_id = $1
`

func (q *Queries) CountSavedJobsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSavedJobsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllSavedJobs = `-- name: DeleteAllSavedJobs :exec
DELETE FROM saved_jobs
WHERE user_id = $1
`

func (q *Queries) DeleteAllSavedJobs(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSavedJobs, userID)
	return err
}

const getMostSavedJobs = `-- name: GetMostSavedJobs :many
SELECT 
    j.id,
    j.title,
    j.company,
    COUNT(sj.user_id) as save_count
FROM jobs j
LEFT JOIN saved_jobs sj ON j.id = sj.job_id
WHERE j.status = 'published'
GROUP BY j.id
ORDER BY save_count DESC
LIMIT $1
`

type GetMostSavedJobsRow struct {
	ID        pgtype.UUID
	Title     string
	Company   string
	SaveCount int64
}

func (q *Queries) GetMostSavedJobs(ctx context.Context, limit int32) ([]GetMostSavedJobsRow, error) {
	rows, err := q.db.Query(ctx, getMostSavedJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMostSavedJobsRow
	for rows.Next() {
		var i GetMostSavedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.SaveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedJobNotes = `-- name: GetSavedJobNotes :one
SELECT notes FROM saved_jobs
WHERE user_id = $1 AND job_id = $2
`

type GetSavedJobNotesParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

func (q *Queries) GetSavedJobNotes(ctx context.Context, arg GetSavedJobNotesParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getSavedJobNotes, arg.UserID, arg.JobID)
	var notes pgtype.Text
	err := row.Scan(&notes)
	return notes, err
}

const getSavedJobsByUser = `-- name: GetSavedJobsByUser :many
SELECT 
    sj.user_id, sj.job_id, sj.saved_at, sj.notes,
    j.title,
    j.company,
    j.location,
    j.job_type,
    j.salary_min,
    j.salary_max,
    j.salary_currency,
    j.remote_possible,
    j.status as job_status
FROM saved_jobs sj
JOIN jobs j ON sj.job_id = j.id
WHERE sj.user_id = $1
ORDER BY sj.saved_at DESC
LIMIT $2 OFFSET $3
`

type GetSavedJobsByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type GetSavedJobsByUserRow struct {
	UserID         pgtype.UUID
	JobID          pgtype.UUID
	SavedAt        pgtype.Timestamp
	Notes          pgtype.Text
	Title          string
	Company        string
	Location       pgtype.Text
	JobType        JobType
	SalaryMin      pgtype.Int4
	SalaryMax      pgtype.Int4
	SalaryCurrency pgtype.Text
	RemotePossible pgtype.Bool
	JobStatus      JobStatus
}

func (q *Queries) GetSavedJobsByUser(ctx context.Context, arg GetSavedJobsByUserParams) ([]GetSavedJobsByUserRow, error) {
	rows, err := q.db.Query(ctx, getSavedJobsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavedJobsByUserRow
	for rows.Next() {
		var i GetSavedJobsByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.JobID,
			&i.SavedAt,
			&i.Notes,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.JobType,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.RemotePossible,
			&i.JobStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavedJobsByUserBasic = `-- name: GetSavedJobsByUserBasic :many
SELECT sj.user_id, sj.job_id, sj.saved_at, sj.notes FROM saved_jobs sj
WHERE sj.user_id = $1
ORDER BY sj.saved_at DESC
`

func (q *Queries) GetSavedJobsByUserBasic(ctx context.Context, userID pgtype.UUID) ([]SavedJob, error) {
	rows, err := q.db.Query(ctx, getSavedJobsByUserBasic, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedJob
	for rows.Next() {
		var i SavedJob
		if err := rows.Scan(
			&i.UserID,
			&i.JobID,
			&i.SavedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isJobSaved = `-- name: IsJobSaved :one
SELECT EXISTS(
    SELECT 1 FROM saved_jobs
    WHERE user_id = $1 AND job_id = $2
) AS is_saved
`

type IsJobSavedParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

func (q *Queries) IsJobSaved(ctx context.Context, arg IsJobSavedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isJobSaved, arg.UserID, arg.JobID)
	var is_saved bool
	err := row.Scan(&is_saved)
	return is_saved, err
}

const saveJob = `-- name: SaveJob :exec

INSERT INTO saved_jobs (user_id, job_id, notes)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, job_id) 
DO UPDATE SET 
    notes = EXCLUDED.notes,
    saved_at = NOW()
`

type SaveJobParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
	Notes  pgtype.Text
}

// Save/Unsave operations
func (q *Queries) SaveJob(ctx context.Context, arg SaveJobParams) error {
	_, err := q.db.Exec(ctx, saveJob, arg.UserID, arg.JobID, arg.Notes)
	return err
}

const unsaveJob = `-- name: UnsaveJob :exec
DELETE FROM saved_jobs
WHERE user_id = $1 AND job_id = $2
`

type UnsaveJobParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
}

func (q *Queries) UnsaveJob(ctx context.Context, arg UnsaveJobParams) error {
	_, err := q.db.Exec(ctx, unsaveJob, arg.UserID, arg.JobID)
	return err
}

const updateSavedJobNotes = `-- name: UpdateSavedJobNotes :exec
UPDATE saved_jobs
SET notes = $3, saved_at = NOW()
WHERE user_id = $1 AND job_id = $2
`

type UpdateSavedJobNotesParams struct {
	UserID pgtype.UUID
	JobID  pgtype.UUID
	Notes  pgtype.Text
}

func (q *Queries) UpdateSavedJobNotes(ctx context.Context, arg UpdateSavedJobNotesParams) error {
	_, err := q.db.Exec(ctx, updateSavedJobNotes, arg.UserID, arg.JobID, arg.Notes)
	return err
}
