// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: survey_questions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSurveyQuestion = `-- name: CreateSurveyQuestion :one
INSERT INTO job_survey_questions (job_id, question_text, expected_answer, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, question_text, expected_answer, sort_order, created_at, updated_at
`

type CreateSurveyQuestionParams struct {
	JobID          pgtype.UUID
	QuestionText   string
	ExpectedAnswer bool
	SortOrder      int32
}

func (q *Queries) CreateSurveyQuestion(ctx context.Context, arg CreateSurveyQuestionParams) (JobSurveyQuestion, error) {
	row := q.db.QueryRow(ctx, createSurveyQuestion,
		arg.JobID,
		arg.QuestionText,
		arg.ExpectedAnswer,
		arg.SortOrder,
	)
	var i JobSurveyQuestion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.QuestionText,
		&i.ExpectedAnswer,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSurveyQuestion = `-- name: DeleteSurveyQuestion :exec
DELETE FROM job_survey_questions WHERE id = $1 AND job_id = $2
`

type DeleteSurveyQuestionParams struct {
	ID    pgtype.UUID
	JobID pgtype.UUID
}

func (q *Queries) DeleteSurveyQuestion(ctx context.Context, arg DeleteSurveyQuestionParams) error {
	_, err := q.db.Exec(ctx, deleteSurveyQuestion, arg.ID, arg.JobID)
	return err
}

const deleteSurveyQuestionsByJob = `-- name: DeleteSurveyQuestionsByJob :exec
DELETE FROM job_survey_questions WHERE job_id = $1
`

func (q *Queries) DeleteSurveyQuestionsByJob(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurveyQuestionsByJob, jobID)
	return err
}

const getSurveyQuestionsByJob = `-- name: GetSurveyQuestionsByJob :many
SELECT id, job_id, question_text, expected_answer, sort_order, created_at, updated_at FROM job_survey_questions
WHERE job_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) GetSurveyQuestionsByJob(ctx context.Context, jobID pgtype.UUID) ([]JobSurveyQuestion, error) {
	rows, err := q.db.Query(ctx, getSurveyQuestionsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobSurveyQuestion
	for rows.Next() {
		var i JobSurveyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.QuestionText,
			&i.ExpectedAnswer,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
