// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTagToJob = `-- name: AssignTagToJob :exec
INSERT INTO job_tags (job_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignTagToJobParams struct {
	JobID pgtype.UUID
	TagID pgtype.UUID
}

// Job-Tag assignments
func (q *Queries) AssignTagToJob(ctx context.Context, arg AssignTagToJobParams) error {
	_, err := q.db.Exec(ctx, assignTagToJob, arg.JobID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, category, description, color)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    color = EXCLUDED.color
RETURNING id, name, category, description, color, created_at
`

type CreateTagParams struct {
	Name        string
	Category    NullTagCategory
	Description pgtype.Text
	Color       pgtype.Text
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getJobTags = `-- name: GetJobTags :many
SELECT t.id, t.name, t.category, t.description, t.color, t.created_at
FROM tags t
JOIN job_tags jt ON t.id = jt.tag_id
WHERE jt.job_id = $1
ORDER BY t.category, t.name
`

func (q *Queries) GetJobTags(ctx context.Context, jobID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getJobTags, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobsByTag = `-- name: GetJobsByTag :many
SELECT j.id, j.title, j.company, j.company_logo, j.company_website, j.company_location, j.description, j.requirements, j.responsibilities, j.benefits, j.job_type, j.experience_level, j.location, j.remote_possible, j.salary_min, j.salary_max, j.salary_currency, j.status, j.published_at, j.closed_at, j.archived_at, j.expires_at, j.posted_by, j.views_count, j.applications_count, j.created_at, j.updated_at
FROM jobs j
JOIN job_tags jt ON j.id = jt.job_id
WHERE jt.tag_id = $1 AND j.status = 'published'
ORDER BY j.published_at DESC
LIMIT $2 OFFSET $3
`

type GetJobsByTagParams struct {
	TagID  pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetJobsByTag(ctx context.Context, arg GetJobsByTagParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsByTag, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.CompanyLogo,
			&i.CompanyWebsite,
			&i.CompanyLocation,
			&i.Description,
			&i.Requirements,
			&i.Responsibilities,
			&i.Benefits,
			&i.JobType,
			&i.ExperienceLevel,
			&i.Location,
			&i.RemotePossible,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.Status,
			&i.PublishedAt,
			&i.ClosedAt,
			&i.ArchivedAt,
			&i.ExpiresAt,
			&i.PostedBy,
			&i.ViewsCount,
			&i.ApplicationsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, category, description, color, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, category, description, color, created_at FROM tags WHERE name = $1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getTagsForJobs = `-- name: GetTagsForJobs :many
SELECT jt.job_id, t.id, t.name, t.category, t.description, t.color, t.created_at
FROM tags t
JOIN job_tags jt ON t.id = jt.tag_id
WHERE jt.job_id = ANY($1::uuid[])
ORDER BY t.category, t.name
`

type GetTagsForJobsRow struct {
	JobID       pgtype.UUID
	ID          pgtype.UUID
	Name        string
	Category    NullTagCategory
	Description pgtype.Text
	Color       pgtype.Text
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) GetTagsForJobs(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetTagsForJobsRow, error) {
	rows, err := q.db.Query(ctx, getTagsForJobs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsForJobsRow
	for rows.Next() {
		var i GetTagsForJobsRow
		if err := rows.Scan(
			&i.JobID,
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, category, description, color, created_at FROM tags
ORDER BY category, name
LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByCategory = `-- name: ListTagsByCategory :many
SELECT id, name, category, description, color, created_at FROM tags
WHERE category = $1
ORDER BY name
`

func (q *Queries) ListTagsByCategory(ctx context.Context, category NullTagCategory) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromJob = `-- name: RemoveTagFromJob :exec
DELETE FROM job_tags
WHERE job_id = $1 AND tag_id = $2
`

type RemoveTagFromJobParams struct {
	JobID pgtype.UUID
	TagID pgtype.UUID
}

func (q *Queries) RemoveTagFromJob(ctx context.Context, arg RemoveTagFromJobParams) error {
	_, err := q.db.Exec(ctx, removeTagFromJob, arg.JobID, arg.TagID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET 
    name = COALESCE(NULLIF($1::text, ''), name),
    category = COALESCE($2, category),
    description = COALESCE($3, description),
    color = COALESCE($4, color)
WHERE id = $5
RETURNING id, name, category, description, color, created_at
`

type UpdateTagParams struct {
	Name        string
	Category    NullTagCategory
	Description pgtype.Text
	Color       pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Color,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}
