// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateUser = `-- name: CreateOrUpdateUser :one
INSERT INTO users (
    github_id, 
    github_username, 
    email, 
    avatar_url, 
    name, 
    github_access_token, 
    github_token_expires_at,
    last_login_at,
    public_repos,
    public_gists,
    followers,
    following,
    hireable,
    blog,
    company,
    location,
    bio,
    twitter_username,
    top_languages,
    contribution_count
)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
ON CONFLICT (github_id) 
DO UPDATE SET 
    github_username = EXCLUDED.github_username,
    email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    name = EXCLUDED.name,
    github_access_token = EXCLUDED.github_access_token,
    github_token_expires_at = EXCLUDED.github_token_expires_at,
    last_login_at = NOW(),
    updated_at = NOW(),
    public_repos = EXCLUDED.public_repos,
    public_gists = EXCLUDED.public_gists,
    followers = EXCLUDED.followers,
    following = EXCLUDED.following,
    hireable = EXCLUDED.hireable,
    blog = EXCLUDED.blog,
    company = EXCLUDED.company,
    location = EXCLUDED.location,
    bio = EXCLUDED.bio,
    twitter_username = EXCLUDED.twitter_username,
    top_languages = EXCLUDED.top_languages,
    contribution_count = EXCLUDED.contribution_count
RETURNING id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count
`

type CreateOrUpdateUserParams struct {
	GithubID             int64
	GithubUsername       string
	Email                pgtype.Text
	AvatarUrl            pgtype.Text
	Name                 pgtype.Text
	GithubAccessToken    pgtype.Text
	GithubTokenExpiresAt pgtype.Timestamp
	PublicRepos          pgtype.Int4
	PublicGists          pgtype.Int4
	Followers            pgtype.Int4
	Following            pgtype.Int4
	Hireable             pgtype.Bool
	Blog                 pgtype.Text
	Company              pgtype.Text
	Location             pgtype.Text
	Bio                  pgtype.Text
	TwitterUsername      pgtype.Text
	TopLanguages         []string
	ContributionCount    pgtype.Int4
}

func (q *Queries) CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createOrUpdateUser,
		arg.GithubID,
		arg.GithubUsername,
		arg.Email,
		arg.AvatarUrl,
		arg.Name,
		arg.GithubAccessToken,
		arg.GithubTokenExpiresAt,
		arg.PublicRepos,
		arg.PublicGists,
		arg.Followers,
		arg.Following,
		arg.Hireable,
		arg.Blog,
		arg.Company,
		arg.Location,
		arg.Bio,
		arg.TwitterUsername,
		arg.TopLanguages,
		arg.ContributionCount,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.Name,
		&i.Role,
		&i.GithubAccessToken,
		&i.GithubTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicRepos,
		&i.PublicGists,
		&i.Followers,
		&i.Following,
		&i.Hireable,
		&i.Blog,
		&i.Company,
		&i.Location,
		&i.Bio,
		&i.TwitterUsername,
		&i.TopLanguages,
		&i.ContributionCount,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users 
WHERE github_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, githubID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, githubID)
	return err
}

const getAdminUsers = `-- name: GetAdminUsers :many
SELECT id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count FROM users 
WHERE role = 'admin'
ORDER BY github_username
`

func (q *Queries) GetAdminUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.GithubUsername,
			&i.Email,
			&i.AvatarUrl,
			&i.Name,
			&i.Role,
			&i.GithubAccessToken,
			&i.GithubTokenExpiresAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicRepos,
			&i.PublicGists,
			&i.Followers,
			&i.Following,
			&i.Hireable,
			&i.Blog,
			&i.Company,
			&i.Location,
			&i.Bio,
			&i.TwitterUsername,
			&i.TopLanguages,
			&i.ContributionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count FROM users 
WHERE github_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.Name,
		&i.Role,
		&i.GithubAccessToken,
		&i.GithubTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicRepos,
		&i.PublicGists,
		&i.Followers,
		&i.Following,
		&i.Hireable,
		&i.Blog,
		&i.Company,
		&i.Location,
		&i.Bio,
		&i.TwitterUsername,
		&i.TopLanguages,
		&i.ContributionCount,
	)
	return i, err
}

const getUserByGitHubUsername = `-- name: GetUserByGitHubUsername :one
SELECT id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count FROM users
WHERE github_username = $1 LIMIT 1
`

func (q *Queries) GetUserByGitHubUsername(ctx context.Context, githubUsername string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubUsername, githubUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.Name,
		&i.Role,
		&i.GithubAccessToken,
		&i.GithubTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicRepos,
		&i.PublicGists,
		&i.Followers,
		&i.Following,
		&i.Hireable,
		&i.Blog,
		&i.Company,
		&i.Location,
		&i.Bio,
		&i.TwitterUsername,
		&i.TopLanguages,
		&i.ContributionCount,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count FROM users 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.Name,
		&i.Role,
		&i.GithubAccessToken,
		&i.GithubTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicRepos,
		&i.PublicGists,
		&i.Followers,
		&i.Following,
		&i.Hireable,
		&i.Blog,
		&i.Company,
		&i.Location,
		&i.Bio,
		&i.TwitterUsername,
		&i.TopLanguages,
		&i.ContributionCount,
	)
	return i, err
}

const isUserAdmin = `-- name: IsUserAdmin :one
SELECT EXISTS(
    SELECT 1 FROM users 
    WHERE github_id = $1 AND role = 'admin'
) as is_admin
`

func (q *Queries) IsUserAdmin(ctx context.Context, githubID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAdmin, githubID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count FROM users 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.GithubUsername,
			&i.Email,
			&i.AvatarUrl,
			&i.Name,
			&i.Role,
			&i.GithubAccessToken,
			&i.GithubTokenExpiresAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicRepos,
			&i.PublicGists,
			&i.Followers,
			&i.Following,
			&i.Hireable,
			&i.Blog,
			&i.Company,
			&i.Location,
			&i.Bio,
			&i.TwitterUsername,
			&i.TopLanguages,
			&i.ContributionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users 
SET role = $2, updated_at = NOW()
WHERE github_id = $1
RETURNING id, github_id, github_username, email, avatar_url, name, role, github_access_token, github_token_expires_at, last_login_at, created_at, updated_at, public_repos, public_gists, followers, following, hireable, blog, company, location, bio, twitter_username, top_languages, contribution_count
`

type UpdateUserRoleParams struct {
	GithubID int64
	Role     string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.GithubID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.Name,
		&i.Role,
		&i.GithubAccessToken,
		&i.GithubTokenExpiresAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicRepos,
		&i.PublicGists,
		&i.Followers,
		&i.Following,
		&i.Hireable,
		&i.Blog,
		&i.Company,
		&i.Location,
		&i.Bio,
		&i.TwitterUsername,
		&i.TopLanguages,
		&i.ContributionCount,
	)
	return i, err
}
