// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_skill_profile.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSkillProfile = `-- name: CreateUserSkillProfile :one
INSERT INTO user_skill_profile (
    user_id,
    backend_score,
    frontend_score,
    devops_score,
    database_score,
    backend_level,
    frontend_level,
    devops_level,
    overall_score
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, backend_score, frontend_score, devops_score, database_score, backend_level, frontend_level, devops_level, overall_score, generated_at
`

type CreateUserSkillProfileParams struct {
	UserID        uuid.UUID
	BackendScore  pgtype.Int4
	FrontendScore pgtype.Int4
	DevopsScore   pgtype.Int4
	DatabaseScore pgtype.Int4
	BackendLevel  pgtype.Text
	FrontendLevel pgtype.Text
	DevopsLevel   pgtype.Text
	OverallScore  pgtype.Int4
}

func (q *Queries) CreateUserSkillProfile(ctx context.Context, arg CreateUserSkillProfileParams) (UserSkillProfile, error) {
	row := q.db.QueryRow(ctx, createUserSkillProfile,
		arg.UserID,
		arg.BackendScore,
		arg.FrontendScore,
		arg.DevopsScore,
		arg.DatabaseScore,
		arg.BackendLevel,
		arg.FrontendLevel,
		arg.DevopsLevel,
		arg.OverallScore,
	)
	var i UserSkillProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BackendScore,
		&i.FrontendScore,
		&i.DevopsScore,
		&i.DatabaseScore,
		&i.BackendLevel,
		&i.FrontendLevel,
		&i.DevopsLevel,
		&i.OverallScore,
		&i.GeneratedAt,
	)
	return i, err
}

const getLatestUserSkillProfile = `-- name: GetLatestUserSkillProfile :one
SELECT id, user_id, backend_score, frontend_score, devops_score, database_score, backend_level, frontend_level, devops_level, overall_score, generated_at FROM user_skill_profile
WHERE user_id = $1
ORDER BY generated_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUserSkillProfile(ctx context.Context, userID uuid.UUID) (UserSkillProfile, error) {
	row := q.db.QueryRow(ctx, getLatestUserSkillProfile, userID)
	var i UserSkillProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BackendScore,
		&i.FrontendScore,
		&i.DevopsScore,
		&i.DatabaseScore,
		&i.BackendLevel,
		&i.FrontendLevel,
		&i.DevopsLevel,
		&i.OverallScore,
		&i.GeneratedAt,
	)
	return i, err
}
