-- +goose Up
-- +goose StatementBegin
ALTER TABLE users ADD COLUMN IF NOT EXISTS public_repos INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS public_gists INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS followers INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS following INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS hireable BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS blog VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter_username VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS top_languages TEXT[] DEFAULT '{}';
ALTER TABLE users ADD COLUMN IF NOT EXISTS contribution_count INTEGER DEFAULT 0;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE users DROP COLUMN IF EXISTS public_repos;
ALTER TABLE users DROP COLUMN IF EXISTS public_gists;
ALTER TABLE users DROP COLUMN IF EXISTS followers;
ALTER TABLE users DROP COLUMN IF EXISTS following;
ALTER TABLE users DROP COLUMN IF EXISTS hireable;
ALTER TABLE users DROP COLUMN IF EXISTS blog;
ALTER TABLE users DROP COLUMN IF EXISTS company;
ALTER TABLE users DROP COLUMN IF EXISTS location;
ALTER TABLE users DROP COLUMN IF EXISTS bio;
ALTER TABLE users DROP COLUMN IF EXISTS twitter_username;
ALTER TABLE users DROP COLUMN IF EXISTS top_languages;
ALTER TABLE users DROP COLUMN IF EXISTS contribution_count;
-- +goose StatementEnd